### ISSUE TITLE
Felix doesn't appear to pin all its dependencies

### ISSUE THREAD

**Issue by tomdee** [projectcalico/felix#1013]
e.g. in https://github.com/projectcalico/calico/blob/master/felix_requirements.txt only a few deps are pinned.

I like the approach used in libcalico, with a `-frozen` file which pins everything (https://github.com/projectcalico/libcalico/blob/master/build-requirements-frozen.txt) and a non-frozen file (https://github.com/projectcalico/libcalico/blob/master/build-requirements.txt) which only lists direct dependencies. This makes it easy to upgrade deps in future.

**Comment by matthewdupre** [comment]
I think I prefer keeping them open ended for Felix: bear in mind that Felix is often not installed inside a virtualenv or container, so it needs to be able to co-exist with other packages that might want later versions.  If we pin them all, either the pin is a lie and we use different versions when installing from packages or we start distributing debs and rpms for a bunch of python modules.

@tomdee?

**Comment by fasaxc** [comment]
Under my golang felix work, I'm rejigging the packaging to ship a virtualenv so I think I'll need to tackle this under that work.

**Comment by fasaxc** [comment]
Need to address this for #1102

**Comment by fasaxc** [comment]
Fixed under #1122.
