### ISSUE TITLE
DNS/BOOTP whitelist rules should be OpenStack-only

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1020]
We currently whitelist bootp and DNS traffic from workloads.  This is needed for OpenStack but it's inappropriate for container deployments.

**Comment by lxpollitt** [comment]
Should we consider moving this function out of Felix and into the OpenStack plugin? i.e. OpenStack includes these in policy of some sort? Or is there a timing thing whereby this is essential to be in place at a particular moment earlier than policy could be applied?

**Comment by fasaxc** [comment]
@lxpollitt I don't think there's a timing issue but it is a path (workload->host) that we don't currently have a good way to apply policy to.  We do apply the workload's egress policy on that path but if that policy allows the packet, we don't immediately accept it: by default, we return it to the existing INPUT policy for further processing.

**Comment by fasaxc** [comment]
@lxpollitt maybe we should add a special "from-workload-to-host" endpoint that you can add policy to?

**Comment by fasaxc** [comment]
Moving out to 2.1.0, should be able to revisit at same time as completing the dataplane driver port to golang.

**Comment by fasaxc** [comment]
Fixed under #1202; we now only program openstack rules if the interface prefix is "tap" or the metadata addresses are explicitly defined.
