### ISSUE TITLE
Bare metal policy - ipv6 endpoint selectors don't cause ipv4 rules to be created

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#1041]
If I configure an endpoint using an `expected_ipv6_addrs` key, (e.g. `/calico/v1/host/calico-st01/endpoint/endpoint1 : {"expected_ipv6_addrs": ["fec0::250:56ff:fe92:365f"], "labels": {"hostname": "calico-st01", "role": "control"}}`) I find that felix does NOT write ipv4 rules for this endpoint.

**Comment by lwr20** [comment]
@fasaxc tells me this is expected behaviour - docs should probably be updated to explain this.

**Comment by fasaxc** [comment]
Moved to caico repo.
