### ISSUE TITLE
Felix should have FailsafeIn/OutboundHostPorts equivalents for UDP as well

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#1064]
The current failsafe ports options only apply to TCP.

There should be equivalent function available for UDP (e.g. DNS) as well.

I can see two obvious approaches:
1. Have the existing options cover both TCP and UDP ports.
2. Change the names, and add extra options (e.g. FailsafeInboundHostUDPPorts).

What do people think on 1 vs 2 vs <something else>?

**Comment by fasaxc** [comment]
Probably less to go wrong with (2)?  Less parsing to do, fewer typo opportunities?

**Comment by fasaxc** [comment]
@matthewdupre I think you're working on this.
