### ISSUE TITLE
etcd data model doc needs clarifications wrt filtering packets and endpoints

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/felix#1069]
http://docs.projectcalico.org/en/latest/etcd-data-model.html explains a lot but:

(1) It does not explain that filtering is done at egress from the source endpoint and again, independently, at ingress to the target endpoint.  Explaining this is very helpful to people learning how this stuff works (e.g., see https://calicousers.slack.com/archives/kubernetes/p1468940203000100).

(2) I wonder if there is a typo in the note saying

> If no policies in a tier match an endpoint then the packet skips the tier completely. The “default deny” behavior described above only applies once one of the profiles in a tier has matched a packet.

Should that last word be "endpoint" rather than "packet"?  Note that the first sentence of that note speaks of matching an endpoint rather than a packet.

**Comment by fasaxc** [comment]
Re (2), yes, that looks like a mistake.  A tier only applies to packets if one of its policies applies to the endpoint.

**Comment by fasaxc** [comment]
Closing because that doc has been retired.
