### ISSUE TITLE
Does calico support to float ip if the docker container restart or transfer another machine?

### ISSUE THREAD

**Issue by yuandy** [projectcalico/felix#1084]

**Comment by fasaxc** [comment]
We discourage people from re-using IPs; Calico allocates IPs for efficient routing (by keeping IPs in the same subnet together on one host).  Re-using an IP on a different host fragments the routing table, which is undesirable.

Is there a particular application that you have in mind or a particular use case that requires re-using an IP?

**Comment by fasaxc** [comment]
Closing as stale
