### ISSUE TITLE
Kubernetes ignoring calico-ipam

### ISSUE THREAD

**Issue by CarlosOVillanueva** [projectcalico/felix#1090]
**OS: COREOS STABLE 1068.10.0**

I have a 3 node k8 cluster running v1.3.6+coreos.0 and calico v1.3.1. I've followed virtually every guideline online and am having zero luck getting k8 to use calico. 

My set up consists of:

1. Flannel not part of deployment
2. Running policy-controller on each kubelet
3. Kubelet.Service includes the network-plugin-dir and network-plugin directives
4. Calico-Node.Service includes the ETCD_AUTHORITY and the exec for calicoctl
5. /opt/bin contains the calicoctl binary
6. /opt/cni/bin contains the calico and calico-ipam binaries
7. /etc/cni/net.d contains the 10-calico.conf

The calico-node and kubelet services come up fine and etcd shows all nodes being in a healthy state. When I run kubectl get svc <NAMEOFSVC> the service is getting an IP from the K8 bridge versus calico (e.g., 172.X.X.X vs 192.X.X.X). 

In any case, any help on this matter would be greatly appreciated! 

calico-node.service

```
  [Unit]
  Description=calicoctl node
  After=docker.service
  Requires=docker.service

  [Service]
  User=root
  Environment="ETCD_AUTHORITY=10.74.81.201:2379"
  Environment="USE_CALICO=true"
  PermissionsStartOnly=true
  ExecStart=/opt/bin/calicoctl node --detach=false
  Restart=always
  RestartSec=10

  [Install]
  WantedBy=multi-user.target
```
kubelet.service
```
  [Unit]
  Description=Kubelet via Hyperkube ACI
  After=calico-node.service k8s-assets.target
  Requires=calico-node.service k8s-assets.target
  [Service]
  ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
  Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log --mount volume=var-log,target=/var/log"
  Environment="KUBELET_VERSION=v1.3.6_coreos.0"
  EnvironmentFile=/etc/environment
  ExecStartPre=/usr/bin/mkdir -p /var/log/containers
  ExecStart=/usr/lib/coreos/kubelet-wrapper \
    --api-servers=http://127.0.0.1:8080 \
    --register-schedulable=true \
    --allow-privileged=true \
    --config=/etc/kubernetes/manifests \
    --hostname-override=10.74.81.201 \
    --cluster_dns=10.3.0.10 \
    --cluster_domain=cluster.local
    --network-plugin-dir=/etc/cni/net.d \
    --network-plugin=cni \
    --logtostderr=true
  Restart=always
  RestartSec=10
  [Install]
  WantedBy=multi-user.target
```

10-calico.conf

```
  {
      "name": "calico-k8s-network",
      "type": "calico",
      "etcd_authority": "10.74.81.201:2379",
      "log_level": "info",
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      }
  }
```

**Comment by caseydavenport** [comment]
@CarlosOVillanueva - `kubectl get svc` will return your Service IP addresses, which are implemented outside of Calico by the kube-proxy.  You shouldn't see Calico IP addresses on your Services.

However, you should see Calico IP addresses on each Kubernetes Pod.  You can check the address:

```shell
kubectl describe pod | grep podIP
```

**Comment by CarlosOVillanueva** [comment]
@caseydavenport - So, I ran the command as you suggested and the only IPs returned come from a 172.17.0.0/16 subnet. From my understanding, that is an IP from K8, not Calico. My Calico Pool only has (192.168.0.0/16) listed. I can manually assign an IP in that subnet when I create a node, but I was under the impression that if I ran calico-node as a service with calico ipam, K8 would do this automatically.

```
user19@jump01 ~/CET/k8/kubernetes/vm/config $ kube describe pod | grep IP
IP:		172.17.0.5
IP:		172.17.0.2
IP:		172.17.0.2
IP:		172.17.0.2
IP:		172.17.0.4
IP:		172.17.0.3
IP:		172.17.0.3
IP:		172.17.0.3
```

**Comment by caseydavenport** [comment]
@CarlosOVillanueva well, that looks like Calico IPAM isn't being used to me :)

You should be able to see what is going on in `/var/log/calico/cni/cni.log` (you might have to set log_level to info, restart the kubelet, and create a pod to get new logs).  That should tell us which IPAM it is trying to use.

There should also be a `/var/log/calico/cni/ipam.log` if Calico IPAM is being called at all.

**Comment by CarlosOVillanueva** [comment]
@caseydavenport : Thanks for the quick response - I appreciate all the help on this.

If you don't mind, please reference the first post. I posted the contents of **/etc/cni/net.d/10-calico.conf** and  **kubernetes.service**. I also have the cni binaries under /opt/cni/bin. These files are present on all kubelets. Based on the online documentation, I believe I have these files configured properly. 

Unfortunately, I do not have a cni directory under **/var/log/calico**, which leads me to believe cni is not firing.

**Comment by caseydavenport** [comment]
Yeah, those files do look correct to me.  If you're not seeing anything in `/var/log/calico`, then your diagnosis sounds logical to me.  Most likely the CNI plugin is not being called by the kubelet.

I noticed that you're using the kubelet-wrapper to launch the kubelet under rkt.  I'm not sure what the default options are, but it doesn't look like you're mounting `/etc/cni/net.d` and `/opt/cni/bin` into the kubelet, which could explain why the plugins aren't being called.

I'm basing that guess on this line:
```
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log --mount volume=var-log,target=/var/log"
```

**Comment by CarlosOVillanueva** [comment]
@caseydavenport : I added the mounts to the RKT options , reloaded the daemon and restarted kubelet on all nodes. Still no love from the kubelet-wrapper :-(.  Is there anything else that tells the wrapper to use CNI?

```
Environment="RKT_OPTS=\
--volume var-log,kind=host,source=/var/log \
--volume cni-plugin,kind=host,source=/etc/cni/net.d \
--volume cni-bin,kind=host,source=/opt/cni/bin \
--mount volume=var-log,target=/var/log \
--mount volume=cni-plugin,target=/etc/cni/net.d \
--mount volume=cni-bin,target=/opt/cni/bin"
```

mount | grep cni
```
/dev/xvda9 on /var/lib/rkt/pods/run/afa4da2a-a8ad-44d3-bcbc-bac7f9014d74/stage1/rootfs/opt/stage2/hyperkube/rootfs/etc/cni/net.d type ext4 (rw,relatime,seclabel,data=ordered)
/dev/xvda9 on /var/lib/rkt/pods/run/afa4da2a-a8ad-44d3-bcbc-bac7f9014d74/stage1/rootfs/opt/stage2/hyperkube/rootfs/opt/cni/bin type ext4 (rw,relatime,seclabel,data=ordered)

```

**Comment by CarlosOVillanueva** [comment]
@caseydavenport : Is this normal behavior for the calico plugin under /opt/cni/bin

```
kube3-core1 bin # ./calico -vh       
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
```

**Comment by caseydavenport** [comment]
That's a bug with the latest CNI plugin and newer versions of CoreOS - it should be benign though (it should still execute properly)

**Comment by caseydavenport** [comment]
It will be fixed in the next release.

**Comment by CarlosOVillanueva** [comment]
Unfortunately, I still can't get the kubelet-wrapper to use CNI. The mounts are there, and I went as far as to compare your settings in your new project **calico-k8s-cluster** to see if there was anything that really stood out. At the end of the day, the only difference I saw was that you actually invoked kubelet vs the kubelet-wrapper.

**Comment by CarlosOVillanueva** [comment]
@caseydavenport: I updated the calico-cni binaries to the latest RC and the undefined symbol error is gone, but it still doesn't look like CNI is working. If you don't mind, can I hit you up on Slack?

**Comment by CarlosOVillanueva** [comment]
Please go ahead and close this issue. It's no longer a problem.

**Comment by sbikram** [comment]
@CarlosOVillanueva , was the issue fixed ? can you provide some details on how did u fix it ?
