### ISSUE TITLE
Fix incompatibility with etcd3 server v2 api

### ISSUE THREAD

**Issue by mikev** [projectcalico/felix#1092]
Calico uses a Python etcd client.  It is currently incompatible with the etcd3 server.  The Etcd3 server correctly enforces best security practices and refuses connections from TLSv1. 

Root cause issue is documented here:
https://github.com/jplana/python-etcd/pull/196

and
https://github.com/projectcalico/calico-containers/issues/1107

**Comment by fasaxc** [comment]
Assigning to me to track releasing an updated python-etcd deb/rpm for OpenStack.  @mikev maybe you should track the new calico/node release witht he fix over in calico-containers?

**Comment by fasaxc** [comment]
Downgrading the priority for OpenStack-based releases, where the need isn't so pressing.  I believe the fix is already shipped in calico-containers.

**Comment by fasaxc** [comment]
Will be fixed by #1102.

**Comment by fasaxc** [comment]
Fixed by #1122
