### ISSUE TITLE
Improve code quality by using static code analysis tools

### ISSUE THREAD

**Issue by cutwater** [projectcalico/felix#1106]
Currently calico project does not provide tools to check code for correctness and PEP8 coding style. The suggestion is to integrate static checks into development process, using **flake8** utility (it includes all pep8 checks and brings some additional ones). It will include several possible stages: manual check performed by developer during working with code, automated check using CI.

**Action items:**
- [ ] Add tox job (env) called "pep8" to run checks
- [ ] Fix major flake8 issues, except those ones, that require code rework
- [ ] Integrate "pep8" job with CI
- [ ] Fix remaining issues

**Comment by fasaxc** [comment]
@cutwater We've now retired the python code on master so PEP-8 doesn't apply any more.  It'd be great to get a golang linter in place though.

**Comment by fasaxc** [comment]
Added gometalinter under #1306
