### ISSUE TITLE
Feature: allow tags in felix profiles to sync across multiple calico clusters

### ISSUE THREAD

**Issue by rzenker** [projectcalico/felix#1108]
We are using calico/felix in a multi-DC environment and it would be very beneficial for there to be a way to write a calico profile to take into account tagged endpoints from other datacenters to allow for additional security isolation.

One idea I had was to allow profiles to work similar to security groups in that we could automatically keep a profile in sync of the endpoint IPs of a specific tag from another DC under `<dc>_<profile name>`.  Then in the local profile we could permit from `<dc>_<profile name>` the ports needed.  A simple side daemon/sync script could keep these up to date.

**Comment by fasaxc** [comment]
@rzenker thanks for the suggestion; it's absolutely something that's on our roadmap.

**Comment by fasaxc** [comment]
Federation of clusters is now supported by Tigera's commercial CNX product, which builds on Calico.
