### ISSUE TITLE
Felix hostname could reasonably be an IP or a hostname: it should work as either.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#1124]
Often Felix isn't running with the same hostname that endpoints intended for it are configured in etcd for.  On the one hand, this is a misconfiguration, but it happens often enough that we should try to mitigate it.

Some possible options (intended for 'mostly' mitigation):
- Try to resolve all hostnames into IPs and compare those.  Problem: if there are endpoints for thousands of hosts, this could take a while.
- Accept both an IP and a hostname (FELIX_IP, FELIX_HOSTNAME); and start pods that match either.
- ????

**Comment by fasaxc** [comment]
There's also an issue with short and long-form hostnames.  `foo` vs `foo.org.com`.  Sometimes we detect one of those from felix but, say OpenStack uses the other.

**Comment by fasaxc** [comment]
See also #1096

**Comment by fasaxc** [comment]
It's also come up form time to time that users need to edit their hostnames.  For example, when a node is turned up it may start without a hostname, then have one configured when it is put into service.  Might be best to key our config off a UUID that we assign and store in a local file?

**Comment by caseydavenport** [comment]
We've solved this for deployments that use `calico/node` by persisting information to a local file for when hostnames change, and ensuring the CNI plugin also uses that file.

Could we do similar for other integrations to close this?

**Comment by tmjd** [comment]
@fasaxc or @neiljerram is this still an issue in OpenStack or do we have a solution there also?

**Comment by neiljerram** [comment]
@tmjd I don't think we did anything for this in OpenStack, but I also don't remember anyone mentioning it recently.  If OpenStack is the only loose end, I think we should close this.
