### ISSUE TITLE
Allow src/dst_nets to be lists of CIDRs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1133]
Currently, we only support a single CIDR per rule, some kinds of match are much easier to express (and possibly more efficient) if you could specify multiple CIDRs in the rule.

I believe iptables does support a list of CIDRs on the `--src` parameter.

**Comment by fasaxc** [comment]
Asked user **sege** about his requirements,

> We have a multi tier architecture and instead of running multiple k8s clusters we want to implement egress rules, default egress block and open up to things outside k8s and then open up. 1-… a lot? 50? 100? dont know, sorry.

**Comment by caseydavenport** [comment]
We currently support multiple egress rules per policy, which is the way this would be done today.

This is an API change, and one that I don't think will make v1.0.0 unless we think this is higher than a P2.

Fixing this later in a compatible way won't be the prettiest.

**Comment by fasaxc** [comment]
Not too ugly though; might be worth doing:  I'd suggest that we support `"net": "10.0.0.1/32"` as an alias for `"nets": ["10.0.0.1/32"]` then deprecate `"net"`.  If a rule has both, just add the `"net"` into the `"nets"` list and carry on.

Our YAML syntax makes the old way particularly verbose, another user asked about it today.

**Comment by fasaxc** [comment]
Fixed by #1483
