### ISSUE TITLE
Felix hangs if FELIX_DATASTORETYPE option is invalid

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#1156]
Without any error message: the process stays running, but writes no logs, programs no iptables rules etc.

Bad:
`FELIX_DATASTORETYPE='' calico-felix`

Good:
`calico-felix
FELIX_DATASTORETYPE='etcdv2' calico-felix`

We'll work around it for now in calico-node, but there should be a proper error message when it's invalid, not just no logs.

**Comment by fasaxc** [comment]
I put up a PR to improve early logging.  FYI, Felix already had a special-case for diagnosing early startup issues.  It'd honour FELIX_LOGSEVERITYSCREEN even before it parsed the rest of the config.

Fix is to default to logging errors or above and to add another env variable to allow early logging (only) to be configured.
