### ISSUE TITLE
v2.0.0 calico/felix container missing a root CA store

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1159]
```2016-11-04 16:45:32.644 [INFO][1] usagerep.go 90: Failed to report usage/get deprecation warnings. error=Get https://usage.projectcalico.org/UsageCheck/calicoVersionCheck?cluster_type=unknown&felix_type=go&git_revision=6526356fa91bdca2a88f70cf89314d634ca30ea6&guid=baddecaf&hostname=smc-ubuntu&num_host_endpoints=0&num_wl_endpoints=0&size=2&version=2.0.0.dev1: x509: failed to load system roots and no roots provided```

**Comment by caseydavenport** [comment]
@fasaxc what is the impact of this?

**Comment by tomdee** [comment]
We don't document that felix should be executed from this container anywhere so low impact right now (though it's a trivial fix to `apk -U add ca-certificates`)
