### ISSUE TITLE
Latest Logrus changes method

### ISSUE THREAD

**Issue by djosborne** [projectcalico/felix#1162]
When updating felix to use pinned libcalico-go, we inadvertently updated logrus which changed functionality of a method felix uses when logging.

I lost the build output to prove it, but I think it can be reproed by `glide up` then building the binary. UT's will display an error.

**Comment by caseydavenport** [comment]
I've pinned this in the v2.0.0-beta.3 glide.yaml, but it will need to go to master as well.

**Comment by neiljerram** [comment]
Is this the problem that is fixed by #1163 ?

**Comment by djosborne** [comment]
Temporarily, yes. Let's keep this open to track implementing the actual fix:
>we should rev to 0.11.0 and fix up our code

**Comment by fasaxc** [comment]
@neiljerram Please can you take a look at this with a view to revving that dependency and fixing up the fallout?
