### ISSUE TITLE
Routes to devices are not restored automatically

### ISSUE THREAD

**Issue by adidenko** [projectcalico/felix#1185]
Routes to "cali*" interfaces are not monitored so they could be removed accidentally which leads to unreachable workload (pod).

**Steps to reproduce:**

on a k8s+calico node remove any route to endpoint:
```
$ ip ro | grep cali
10.233.120.130 dev calia44f8339e4a  scope link 
$ ip ro del 10.233.120.130
```

**Expected result:**
route recovers

**Actual result:**
route is missing

**Version**
calico/node:v1.0.0-beta

**Workaround:**
On a problem node execute:
```
docker exec -t -i calico-node killall -HUP calico-felix
```

**Comment by fasaxc** [comment]
With a bit of luck, we should be able to design this out of the golang dataplane driver #1171.

**Comment by AlexeyKasatkin** [comment]
This https://github.com/projectcalico/felix/pull/1202 was merged. It uses netlink.LinkUpdate and update routes on link state change. But, AFAIC, to solve this issue we need to consider netlink.RouteUpdate as well.
