### ISSUE TITLE
Neutron port updates for ports that are status down, are not reflected on the hypervisor by Felix.

### ISSUE THREAD

**Issue by jocado** [projectcalico/felix#1208]
Hi.

Using calico 1.4 with openstack Mitaka.

We can have multiple IPs on the same port, a VIP, in addition to the *main* instance IP.
If an instance is shutdown, or fails for some reason, we need to move the VIP to another instance.  We can update the Neutron port configs, remove the IP from the first port, and add it to the second port.  Everything works for the new instance.
However, the hypervisor for the first instance [ which may or may not be a different hypervisor used for the second instance ] still has a local route, for the VIP, on the original tap interface for the first instance.
This can cause problems, especially if an instance on the first hypervisor needs to communicate with the second instance [ which may be on a new hypervisor ], which fails, as the hypervisor essentially black holes the traffic by routing it to the tap interface of the first instance [ which is down ].

Essentially, we can end up with a situation like this on two hypervisors:

```
hypervisor1 # ip r s |grep tape3957b74-5a
10.1.2.188 dev tape3957b74-5a  scope link 
10.1.2.195 dev tape3957b74-5a  scope link 
```

```
hypervisor2 # ip r s |grep tap677220a2-ad
10.1.2.194 dev tap677220a2-ad  scope link 
10.1.2.195 dev tap677220a2-ad  scope link 
```

Hopefully this makes sense - please let me know if you need to clarify further :)

This might all be by design, but the above scenario is problematic for us.

It might be nice to have a config option available in felix to withdraw the routes for interfaces that are status down, or something like that.

If we start the first instance again, the route for the VIP is removed from the tap interface on the hypervisor, but we might not be able or want to do that for various reasons.
I presume deleting the instances would also remove the old route tap, but again that might not be desirable.

Thanks in advance for any help and thoughts on this.

Cheers,
Just

**Comment by neiljerram** [comment]
Hmm, I think I'd expect this to work, i.e. for the route to be withdrawn on the old hypervisor.

Do you by any chance know what this scenario looks like in terms of the port updates that Neutron passes into the ML2 mechanism driver?  You could probably get these by grepping for 10.1.2.195 in the Neutron server log.

**Comment by fasaxc** [comment]
How this should work:

- If Felix is told that the endpoint is `"state": "inactive"` (which should be mapped through from "port down" by networking-calico) then this branch should remove the routes: https://github.com/projectcalico/felix/blob/master/python/calico/felix/endpoint.py#L711 
- That code path should also get hit by an endpoint being removed.  
- If the tap interface itself goes down at the kernel level then the kernel removes the routes.
- If the whole host fails, the failure of the BGP connection should withdraw the route (after a timeout).

> If an instance is shutdown, or fails for some reason.

@jocado Can you give us some more detail on a particular scenario that causes the bad behaviour?  IT'd be great to have a sequence of steps we can try on our own system that reproduces the problem.  Failing that, it'd be helpful to have the neutron server logs and felix logs (at debug level if possible).

**Comment by jocado** [comment]
Thanks guys.
Sure - I'll get the process to reproduce and some logs together tomorrow.

**Comment by jocado** [comment]
After a little more investigation, and running felix in debug mode, I think I've found the important line in the felix logs.

Steps to reproduce first...

This example is for an instance with initial IP `10.1.2.6`, on port `7f622ff0-71c2-4139-966e-5fb55b683f54` , and subnet `5e7f4836-32ca-4f44-b3d8-8a12c58661ad`.  Extra IP will be `10.1.2.7`


Add extra IP using port-update specifying initial IP and a new one.

```
neutron port-update --fixed-ip subnet_id=5e7f4836-32ca-4f44-b3d8-8a12c58661ad,ip_address=10.1.2.6 --fixed-ip subnet_id=5e7f4836-32ca-4f44-b3d8-8a12c58661ad,ip_address=10.1.2.7 7f622ff0-71c2-4139-966e-5fb55b683f54
```

Check interfaces on hypervisor:

```
# ip r s | grep 7f622ff0
10.1.2.6 dev tap7f622ff0-71  scope link 
10.1.2.7 dev tap7f622ff0-71  scope link
```

Shutdown instance, gracefully or otherwise.
Then remove on extra IP by updating the port with only the first IP.

```
neutron port-update --fixed-ip subnet_id=5e7f4836-32ca-4f44-b3d8-8a12c58661ad,ip_address=10.1.2.6 7f622ff0-71c2-4139-966e-5fb55b683f54
```

Check interfaces on hypervisor:

```
# ip r s |grep 7f622ff0
10.1.2.6 dev tap7f622ff0-71  scope link 
10.1.2.7 dev tap7f622ff0-71  scope link
```

...route still exists :(


It may be a red herring, but in the felix debug output, I see something that seems quite relevant.

```
2016-12-06 15:00:33,675 [DEBUG][3294/34] calico.felix.endpoint 747: Endpoint update pending: {'ipv4_gateway': '10.1.2.1', 'ipv4_subnet_ids': [u'5e7f4836-32ca-4f44-b3d8-8a12c58661ad'], 'name': u'tap7f622ff0-71', 'state': 'active', 'ipv6_subnet_ids': [], 'ipv6_nets': [], 'mac': 'fa:16:3e:b8:97:17', 'ipv4_nets': ['10.1.2.6/32'], 'profile_ids': ['openstack-sg-0a1fdc56-955e-42a6-bcda-c3ff311ecf30']}
2016-12-06 15:00:33,675 [DEBUG][3294/34] calico.felix.endpoint 934: IP addresses changed, need to update routing
2016-12-06 15:00:33,676 [DEBUG][3294/34] calico.felix.endpoint 947: Set of all IPs changed from set(['10.1.2.6', '10.1.2.7']) to set(['10.1.2.6'])
2016-12-06 15:00:33,676 [DEBUG][3294/34] calico.felix.endpoint 772: Device is out-of-sync, trying to configure it
2016-12-06 15:00:33,676 [DEBUG][3294/34] calico.felix.endpoint 1064: Device is known to be down, skipping attempt to configure it.
```

Do you need any more info than that?

Cheers,
Just

**Comment by fasaxc** [comment]
Thanks @jocado that looks like the smoking gun.  I think we're expecting that a device going down is being deleted so its routes will be removed for us but that's not the case here.

**Comment by jocado** [comment]
No probs.

Shutting down an instance in a cloud is kind of unusual I guess, but does happen.  What may be more common, although still not incredibly frequent, is that in instance can crash.
We've seen qemu processes die, and of course the device and associated routes remain.  That's what made us look into this issue initially.

If I can do anything else to help or test, please let me know.

**Comment by fasaxc** [comment]
Hmm, when I try to reproduce this locally, by running `ip link set down <interface>` then the routes are removed from the kernel when I set the interface down.  @jocado what state is your interface in when the VM is down `ip link show` should give us what we need.  Maybe it's "UP" but not "oper UP", for example.

**Comment by fasaxc** [comment]
> We've seen qemu processes die, and of course the device and associated routes remain. That's what made us look into this issue initially.

Yes, I'd be interested to know what `ip link show` gives in that case, we're generally expecting the kernel to remove the route when the interface goes down but there are several levels of "down" so it looks like you're hitting a different one to our tests.

**Comment by jocado** [comment]
It does seem to go from UP to DOWN

Before
```
# ip l show tap7f622ff0-71
15: tap7f622ff0-71: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 500
    link/ether 00:61:fe:ed:ca:fe brd ff:ff:ff:ff:ff:ff
```

After graceful shutdown from inside the instance
```
# ip l show tap7f622ff0-71
15: tap7f622ff0-71: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 500
    link/ether 00:61:fe:ed:ca:fe brd ff:ff:ff:ff:ff:ff
```

After killing the qemu process.
```
# ip l show tap7f622ff0-71
15: tap7f622ff0-71: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 500
    link/ether 00:61:fe:ed:ca:fe brd ff:ff:ff:ff:ff:ff
```

**Comment by jocado** [comment]
Sorry - didn't mean to close it! :)

**Comment by fasaxc** [comment]
Aha, it's `UP` in the flags but its `DOWN` in the operstate:

`tap7f622ff0-71: <...,UP>` vs. `state DOWN`

**Comment by jocado** [comment]
I've backported this patch to 1.4.4-1-trusty -  `endpoint.py` patches fine.
I've tested it and it seems to work great, normal shutdown or killing the instance.

Thanks all!

Cheers,
Just
