### ISSUE TITLE
Rules with IPv4 CIDRs and no IP version render unintuitively in IPv6

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1212]
If you have a rule with `"src_net": "10.0.0.0/16"` but no IP version field then, when rendering the IPv6 version of the rule, we skip over the IPv4 CIDR resulting in a less-constrained rule.  If the CIDR is the only constraint, we can end up with a blanket allow/deny rule, which is unlikely to be what the user is expecting.

Workaround is to always specify the "ip_version" on the rule in a mixed IPv4/v6 environment.

**Comment by fasaxc** [comment]
I feel like there are two cases here:

- User creates a rule without specifying the IP version, but they use an IPv4 CIDR so they implicitly expect it to be an IPv4 rule.  If a rule has IPv4 CIDRs in it, I think we can assume that it's an IPv4 rule and hence it shouldn't match IPv6 traffic.  This matches the behaviour added for ICMP in #1211.
- User creates a rule with mixed IPv4 and IPv6 CIDRs so it's not clear what they're expecting.  We should validate against that case in libcalico.

**Comment by fasaxc** [comment]
@lwr20 the fix should be in 2.0.0-rc4, passing to you to triage for retest.

**Comment by caseydavenport** [comment]
As per https://github.com/projectcalico/felix/pull/1213#issuecomment-266792062, this looks fixed.
