### ISSUE TITLE
make release doesn't work on a mac

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1216]
Make release fails on a mac for at least this reason:

```
# Check that the executable is correctly statically linked.
ldd bin/calico-felix | grep -q "not a dynamic executable"
/bin/sh: ldd: command not found
```

We should be containerizing all the things.

**Comment by fasaxc** [comment]
See also #1266

**Comment by fasaxc** [comment]
Above issue is now fixed (ldd call moved inside container).  Remaining issues that I'm aware of:

- [ ] deb/RPM scripts run outside container
- [ ] some issue with building the protobuf outside GOPATH
- [ ] `glide up` not containerised

**Comment by caseydavenport** [comment]
I'll add that the `realpath` tool isn't installed on mac by default.  Not sure if the above PR removed the need for that.
