### ISSUE TITLE
Redirect denial logs to a log file

### ISSUE THREAD

**Issue by gnavgire** [projectcalico/felix#1219]
The iptables rule added at the end to LOG the denial packets go to /var/log/messages. Instead can they be logged to other log file ?

**Comment by neiljerram** [comment]
I would guess this is a matter of the metadata fields (category, severity etc.) that the kernel logs those denials with, and then of your local logging configuration (e.g. /etc/rsyslog.conf).

**Comment by neiljerram** [comment]
(So I don't think it's to do with Felix code, or with something that the Felix code controls.)
