### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [projectcalico/felix#1225]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product :)

Michiel

**Comment by fasaxc** [comment]
@chiel1980 I don't believe we have had an external audit but it'd be great to get that kind of validation of the product and to resolve any issues that it finds.  Are you on our slack; it'd be great to discus the logistics and make sure we have an appropriate channel to report any security bugs privately so we can fix them before they are published.

CC @lxpollitt

**Comment by lxpollitt** [comment]
@chiel1980 We know that some users have done security reviews focussed on particular areas they care about, but we don't have details to share or know the full scope of what people have done to date.  Having an external company do a security code review would be very interesting and useful to the community I think.  As @fasaxc suggests, the only thing I would ask is that if issues are found we do not publish the results until we have a release available to address them which would be a high priority task obviously.  (I think publishing significant vulnerabilities without having a release that addresses the vulnerability puts the community at risk.)

Let us know how we can help.  Easiest way to stay in touch is via https://slack.projectcalico.org.  We can set up a private channel for discussion during the review if that would be helpful.

**Comment by fasaxc** [comment]
Closing since this issue hasn't been commented on in over a year.
