### ISSUE TITLE
Deb/RPM release process poorly documented

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1237]
@robbrockbank couldn't figure out how to do it from RELEASING.md, I think that means we need to document it more thoroughly (or even better containerise + automate it).

**Comment by fasaxc** [comment]
@neiljerram, you're probably the best person to document the process.  I'd only be mudding through.

**Comment by neiljerram** [comment]
I've possibly covered this as part of #1239. I'll add you both as reviewers there.

**Comment by fasaxc** [comment]
Agreed.
