### ISSUE TITLE
Felix fails when a host endpoint resolves to a sub-interface

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1280]
Reported by **sicoby** on calico-users slack:

> When configuring a sub interface `calico.felix.endpoint 1022: Interface enp3s0f0.803@enp3s0f0 configured` but this causes felix to crash - `iptables-restore v1.4.21: interface name 'enp3s0f0.803@enp3s0f0' must be shorter than IFNAMSIZ (15)`

They said they were configuring the interface based on IP address.  It appears that, when we're resolving the interface name, we're getting the `@enp3s0f0` suffix from `ip addr/link` and failing to remove it.

**Comment by ragarcia26** [comment]
Would improving the regex on line 151 of https://github.com/projectcalico/felix/blob/master/python/calico/felix/devices.py fix this?

**Comment by fasaxc** [comment]
@ragarcia26 That's likely for Calico 2.0.x, but in 2.1.0, we're replacing that code with a golang version so we need to make sure that version isn't vulnerable to the issue.

**Comment by fasaxc** [comment]
@ragarcia26 Please can you retest with Calico v2.1.0-rc1, which may fix the issue?  We haven't explicitly tested that case here yet but it'd be good to know if the rework in 2.1.0 fixes it.

**Comment by ragarcia26** [comment]
Can confirm that Felix is securing the sub-interface correctly.

**Comment by fasaxc** [comment]
Great, I've added it to our backlog of automated tests that we should add.
