### ISSUE TITLE
Felix and kube-proxy can clobber each other's iptables updates

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1325]
Seen in a scale run with kube-proxy 1.5.2, this script reproduces the issue:
```
#!/usr/bin/env bash

failed=false

function felix () {
    while true; do
        echo -n a
        iptables-restore --noflush --verbose <<EOF
*filter
:felix -
--append felix -m comment --comment "FELIX-A"
COMMIT
EOF
        echo -n A
        echo -n b
        iptables-restore --noflush --verbose <<EOF
*filter
:felix -
--append felix -m comment --comment "FELIX-B"
COMMIT
EOF
        echo -n B
        if iptables-save | grep -q FELIX-A; then
          echo
          echo "FELIX-B update was clobbered"
          failed=true
          return 1
        fi
        echo -n C
    done
}

function kube () {
    while ! ${failed}; do
       echo -n k
       iptables-restore --noflush --verbose <<EOF
*filter
:kube -
COMMIT
EOF
        echo -n K
    done
}


kube &
kube_pid=$!
felix; kill $kube_pid

```

When I run that locally, I see output like this:

```
# ./ipt-clash-repro.sh 
akKkAbKkBCaKkAbKkBKkCaKkAbKkBKkCaKkAbKkKkKkBKkCaKkAbBKk
FELIX-B update was clobbered
```

Confusingly, however, this script, which is identical apart from adding an extra update to the FELIX-B iptables-restore call, exhibits compare-and-swap behaviour.  The update is never clobbered but the kube loop's updates fail if there's a concurrent modification:

```
#!/usr/bin/env bash

failed=false

function felix () {
    while true; do
        echo -n a
        iptables-restore --noflush --verbose <<EOF
*filter
:felix -
--append felix -m comment --comment "FELIX-A"
COMMIT
EOF
        echo -n A
        echo -n b
        iptables-restore --noflush --verbose <<EOF
*filter
:felix -
--append felix -m comment --comment "FELIX-B"
--append felix -m comment --comment "extra update"
COMMIT
EOF
        echo -n B
        if iptables-save | grep -q FELIX-A; then
          echo
          echo "FELIX-B update was clobbered"
          failed=true
          return 1
        fi
        echo -n C
    done
}

function kube () {
    while ! ${failed}; do
       echo -n k
       iptables-restore --noflush --verbose <<EOF
*filter
:kube -
COMMIT
EOF
        echo -n K
    done
}


kube &
kube_pid=$!
felix; kill $kube_pid
```

**Comment by matthewdupre** [comment]
That's depressing.  I'd hoped that since the chains were orthogonal they'd place nice.

**Comment by matthewdupre** [comment]
For anyone reading this; the symptoms are approximately as follows.
1. Connectivity sometimes not as expected following a change (to policies, or a new pod).
2. Connectivity returns to expected behavior later (usually the next IptablesRefreshInterval; which defaults to 60 seconds).

It's a fairly rare occurrence: I think it's unlikely you'll see it unless there's heavy iptables churn coming from Felix and somewhere else (kube-proxy in our case).

**Comment by fasaxc** [comment]
OK, I think I've tracked down why the above code shows rules being clobbered while other tests seem to show a CaS-like behaviour.  The kernel does do a CaS but it compares the old and new _number of_ entries rather than using a sequence number, say.

I think this is the relevant part of the kernel code: 
```
	/* Check inside lock: is the old number correct? */
	if (num_counters != private->number) {
		pr_debug("num_counters != table->private->number (%u/%u)\n",
			 num_counters, private->number);
		local_bh_enable();
		*error = -EAGAIN;
		return NULL;
	}
```
https://github.com/torvalds/linux/blob/master/net/netfilter/x_tables.c#L1129

**Comment by fasaxc** [comment]
Closing now we have a work-around in place.
