### ISSUE TITLE
Emit clear log when Felix is shutting down, done re-syncing.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1345]
For example, when running as a Kubernetes pod, it would be useful to get timestamps for when the kubelet killed the Calico pod on a given node, and then when the kubelet started the Pod again.

Basically, we want to know the difference in time between:
- Felix gets shutdown signal.
- Felix comes back up, finishes syncing dataplane for first time.

This will help debug when Felix isn't running and thus policy isn't being updated for that node.

**Comment by fasaxc** [comment]
As long as we're being shut down gracefully (SIGTERM), you should get this log: https://github.com/projectcalico/felix/blob/master/felix.go#L382
If we're being SIGKILLed, we don't get to write a log.

We do get a log when we're in sync, but not when we finish the subsequent apply to the dataplane:
https://github.com/projectcalico/felix/blob/master/intdataplane/int_dataplane.go#L434
