### ISSUE TITLE
Felix rule interfering with KVM guest

### ISSUE THREAD

**Issue by jaxxstorm** [projectcalico/felix#1346]
I have a quirky problem. I'm running both docker and KVM on my kubernetes hosts running calico (don't ask) and I found outbound connectivity wasn't working from KVM guests.
I narrowed it down to this felix iptables chain:

```
Chain felix-FORWARD (1 references)
num  target     prot opt source               destination
1    DROP       all  --  anywhere             anywhere             ctstate INVALID
2    ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
3    felix-FROM-ENDPOINT  all  --  anywhere             anywhere
4    felix-TO-ENDPOINT  all  --  anywhere             anywhere
5    ACCEPT     all  --  anywhere             anywhere
6    ACCEPT     all  --  anywhere             anywhere
7    felix-FROM-HOST-IF  all  --  anywhere             anywhere
8    felix-TO-HOST-IF  all  --  anywhere             anywhere
```
and in particular, this rule:
```
1    DROP       all  --  anywhere             anywhere             ctstate INVALID
```

if I remove it, everything works again. Is there anything I can do to not have this rule applied? I think it's been added the nat-outgoing option in Calico as far as I can tell

**Comment by fasaxc** [comment]
@jaxxstorm There's no configurability for that rule right now.  We could make it configurable but I think it'd be better to push it down into the per-endpoint chains; that way it only applies to traffic that "belongs" to Calico.

**Comment by fasaxc** [comment]
@jaxxstorm On slack, I think you said this issue was a red-herring (actually a kube-proxy rule that was breaking your set-up).  Can this be closed?

**Comment by jaxxstorm** [comment]
Yep, apologies!
