### ISSUE TITLE
Under churn with k8s, golang DP driver thinks KUBE-SEP chain out-of-sync

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1349]
Under churn tests, we're seeing logs like this:
```
2017-02-16 22:24:01.608 [WARNING][32] table.go 444: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string(nil) chainName="KUBE-SEP-WE2O5CDAE2MDKF6F" expectedRuleIDs=[]string{} ipVersion=0x4 table="nat"
```
_Probably_ benign since the later stage of processing will spot that there's nothing to do but we should squash this false positive.

**Comment by neiljerram** [comment]
Looking at the code change, I'm not sure I understand precisely what was causing that warning (and therefore I'm not sure I understand the fix).

My best guess is that:
- dpHashes was nil, or an empty slice, or perhaps a slice with one "" element
- expectedHashes was a slice with the same number of elements as rules in the chain, all ""
- and hence they aren't DeepEqual.

Is that somewhere close?

**Comment by fasaxc** [comment]
@neiljerram Yes, the problem was that we were iterating over the chains that we thought should be there and checking if they were out of sync.

If a chain that we thought was there had been removed, then the logic went:

- get the chain we read back from `dpHashes` (a `nil` slice)
- calculate what we expect to be in that chain given that (a) it has length 0 and (b) we have no insertions in that chain (a 0-length slice)
- compare the two but a `nil slice != 0-length slice`

**Comment by neiljerram** [comment]
Thanks.  In general, I think it would be good to put more of this kind of detail in the Git commit message.
