### ISSUE TITLE
Ability to enable iptables Log

### ISSUE THREAD

**Issue by rikatz** [projectcalico/felix#1351]
Don't know if this is a feature request, if already exists, but...

Is there a way to make calico create the IPTables rules with a -j LOG also? Like enable logging of every rule hit that happens in a Namespace?

Thanks!

**Comment by fasaxc** [comment]
Yes, each rule supports a `logPrefix` field, which causes that rule to be logged as well.  There's also a `log` action, which only logs and doesn't do anything else.

The log action is documented here: http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/policy

logPrefix seems to be missing, I'll raise an issue for that.

**Comment by fasaxc** [comment]
https://github.com/projectcalico/calico/issues/518

**Comment by DreadPirateShawn** [comment]
The linked issue projectcalico/calico#518 has a comment saying "Think we've removed that field in a clean-up exercise" and was subsequently closed...

Does that mean that the logPrefix support, eg causing a rule to be logged, is no longer supported?

Given that the policy actions are "allow / deny / log / pass", does that mean that the only way to log denied traffic is to duplicate every "deny" rule with a corresponding identical "log" rule?

**Comment by fasaxc** [comment]
Yes, you need to use a separate log rule (at least for now).  The logPrefix feature turned out to be confusing and "painted us into a corner" on some other features.

**Comment by DreadPirateShawn** [comment]
Roger, fair enough -- thanks for the clarification / confirmation.

**Comment by mmueen** [comment]
If we create duplicate rule entry for logging denied traffic, the log entry doesn't contain information if the packet was denied or granted .. we need to log both Accepted and Denied packets, and we can't differentiate between two logs ..

**Comment by acobaugh** [comment]
Is there a reason this issue was closed? It would be tremendously helpful when debugging rules, and required in certain regulatory environments to be able to log at least denies, if not allows as well.
