### ISSUE TITLE
calico 1.6 iptables not update

### ISSUE THREAD

**Issue by mushixun** [projectcalico/felix#1360]
I used calico 1.6,when config the policy rule to iptables,find the iptables not update,but use calico 1.5 is ok,who know why?
![image](https://cloud.githubusercontent.com/assets/10143373/23240009/b28df574-f9a5-11e6-86d0-e43a72cf1a60.png)

**Comment by fasaxc** [comment]
@mushixun We're going to need more information.  

What type of system are you running (k8s, bare-metal, OpenStack, docker etc)?
What steps did you take to upgrade?

**Comment by mushixun** [comment]
I use docker 1.12.6,is the new install。

**Comment by fasaxc** [comment]
Please can you give us a detailed set of steps to reproduce the problem and a description of the symptoms?

**Comment by fasaxc** [comment]
I'm going to close this because it hasn't had any responses for a while.  Please open a new issue if you're still having issues.  Note: Calico 2.1 is now released so I recommend trying that before filing issues against 1.6.
