### ISSUE TITLE
felix agent restarts every 3 seconds when wrong config option added

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/felix#1377]
While trying to modify failsafe rules, I incorrectly ran the following:

calicoctl config set FailsafeOutboundHostPort 80 --raw=felix

When I should have used FailsafeOutboundHostPorts (my version was missing the "s" at the end).  There was no error returned from the calicoctl config set command.  Once I did this, I noticed that the iptables rules were not being updated by felix.  Eventually I realized that the felix agent (in calico-node) was being restarted every 2-3 seconds.  I have attached the felix log for after I tried restarting calico-node hoping that would help (it didn't).  I talked to Matt Dupre via slack, who helped me find this bad config, it appears base on line 106 in the log that felix really didn't like the wrong config option I added.

I was able to fix the problem by unsetting the bad config option, but Matt suggested I write an issue.  Felix agent should handle a wrong config option better, maybe by ignoring it (putting a WARNING in the felix log?) or at the least not letting this kill felix completely.

[felix_log.txt](https://github.com/projectcalico/felix/files/827927/felix_log.txt)

**Comment by fasaxc** [comment]
@bradbehle What version of Felix are you running.  I believe this is fixed in our upcoming 2.1.0 release.  Please can you try with our latest 2.1.0 RC?

**Comment by bradbehle** [comment]
I'll give it a try when we move to 2.1.0.  Thanks.

**Comment by fasaxc** [comment]
Tested this in 2.1.0-rc6 and Felix now ignores bad config values.

**Comment by bradbehle** [comment]
Thanks!
