### ISSUE TITLE
Felix can fail if IPv6 is enabled but some kernel modules are missing.

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1411]
If we're running in a container and hence can't load kernel modules then Felix can try to do IPv6 operations and fail.  For example, if the iptables_ipv6 module is missing: https://github.com/projectcalico/calicoctl/issues/1242

**Comment by tmjd** [comment]
@fasaxc Should this remain open? Looking at the issue you referenced I feel like this issue can probably be closed too.
