### ISSUE TITLE
Felix doesn't respect IpInIpEnabled when configured via KDD

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1452]
When the KDD is configured to use IPIP + BGP, Felix sets the `K8sDisableNodeWatch` option based on the FELIX_IPINIPENABLED environment variable.  However, once config comes in over the Syncer which says IPIP is actually enabled (or disabled), Felix doesn't restart the syncer with the correct value for K8sDisableNodeWatch.

Workaround is in https://github.com/projectcalico/calico/pull/772/files.

## Steps to Reproduce (for bugs)
1. Download KDD BGP Calico manifest on Kubernetes - http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.6/calico.yaml
2. Ensure FELIX_IPINIPENABLED is unset in the environment
3. Notice that IPIP doesn't work.

**Comment by fasaxc** [comment]
@caseydavenport Are you sure the syncer is sending the flag update and the client's List() operation is working?  Felix's approach to dealing with such a config change is to die and be restarted.  Then it loads the config at start-of-day using a  `List()` operation.

**Comment by fasaxc** [comment]
@caseydavenport Explained the issue on slack.  Problem was that the Syncer config gets passed down from the datastore client and the datastore client was only created once, before we load the config.
