### ISSUE TITLE
calico-felix 2.2.0 causes Linux kernel panic on ppc64le platform

### ISSUE THREAD

**Issue by ligc** [projectcalico/felix#1454]
We deployed several Calico clusters with the latest calico code, there are some nodes in the clusters randomly down because of the kernel panic, the kernel panic message shows that it is related to calico-felix. Here is the console output when the kernel panic:

```
Ubuntu 16.04.2 LTS cluster-1494429943211-worker2 hvc0
cluster-1494429943211-worker2 login: [  932.805344] Unable to handle kernel paging request for data at address 0xbfffffffc1abc000
[  932.805433] Faulting instruction address: 0xc0000000002b3014
[  932.805479] Oops: Kernel access of bad area, sig: 11 [#1]
[  932.805515] SMP NR_CPUS=2048 NUMA pSeries
[  932.805569] Modules linked in: ipt_REJECT nf_reject_ipv4 xt_nat xt_tcpudp xt_recent xt_multiport xt_comment xt_set xt_mark iptable_raw ip_set_hash_ip ip_set_hash_net ip_set nfnetlink ipip tunnel4 ip_tunnel veth ipt_MASQUERADE nf_nat_masquerade_ipv4 xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc aufs isofs vmx_crypto input_leds joydev ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_generic usbhid hid ibmvscsi
[  932.806326] CPU: 1 PID: 11847 Comm: calico-felix Not tainted 4.4.0-75-generic #96-Ubuntu
[  932.806381] task: c0000000c1d52a20 ti: c0000000f95fc000 task.ti: c0000000f95fc000
[  932.806434] NIP: c0000000002b3014 LR: c0000000002b30e4 CTR: c000000000009458
[  932.806488] REGS: c0000000f95ff9e0 TRAP: 0300   Not tainted  (4.4.0-75-generic)
[  932.806541] MSR: 8000000000009033 <SF,EE,ME,IR,DR,RI,LE>  CR: 24422008  XER: 00000000
[  932.806688] CFAR: 0000000000063268 DAR: bfffffffc1abc000 DSISR: 40000000 SOFTE: 1 
GPR00: c0000000002b30e4 c0000000f95ffc60 c0000000015f7f00 0000000000000000 
GPR04: 00000000026000c0 ffffffffffffffff 0000000000009d97 c0000000ffe9ff00 
GPR08: 00000000feed0000 bfffffffc1abc000 0000000000000000 0000000000000c01 
GPR12: 0000000000002200 c00000000fb40980 c0000000c1cc0000 0000000000000020 
GPR16: 0000000000000067 0000000000000011 0000000000000039 0000000000000008 
GPR20: 0000000000000010 0000000000000001 c0000000c1d52a20 0000000000000000 
GPR24: 0000000000000000 c00000000178ae80 c0000000fe01f100 c0000000000b66c0 
GPR28: ffffffffffffffff 00000000026000c0 0000000000000000 c0000000fe01f100 
[  932.807407] NIP [c0000000002b3014] kmem_cache_alloc_node+0x124/0x360
[  932.807452] LR [c0000000002b30e4] kmem_cache_alloc_node+0x1f4/0x360
[  932.807497] Call Trace:
[  932.807516] [c0000000f95ffc60] [c0000000002b30e4] kmem_cache_alloc_node+0x1f4/0x360 (unreliable)
[  932.807602] [c0000000f95ffcc0] [c0000000000b66c0] copy_process.isra.5+0x250/0x1870
[  932.807665] [c0000000f95ffda0] [c0000000000b7eb8] _do_fork+0xa8/0x4b0
[  932.807720] [c0000000f95ffe30] [c000000000009460] ppc_clone+0x8/0xc
[  932.807773] Instruction dump:
[  932.807801] 81810008 eb21ffc8 eb41ffd0 7c0803a6 eb61ffd8 eb81ffe0 7d908120 eba1ffe8 
[  932.807893] ebc1fff0 ebe1fff8 4e800020 e95f0022 <7f29502a> 39400000 88ad02ca 994d02ca 
[  932.809503] ---[ end trace ab39c0e1aeafa752 ]---
[  932.811049] 
[  934.811268] Kernel panic - not syncing: Fatal exception
[  934.814237] Rebooting in 10 seconds..
```

## Steps to Reproduce (for bugs)

we were not able to reproduce this issue manually, it only occurs in an automated deployment process. We could provide more debugging information when required.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):  Version:            2.2.0-pre1-89-g345c065
Full git commit ID: 345c065adeac765c65e44824d4ade31d315a74e1
Build date:         2017-05-08T06:09:00+0000

* And/Or, `calico/node` container version (if running Felix in a container): calico_node_ppc64le:1.1.3
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.5.2
* Etcd version (if using etcd datastore driver):  2.3.7
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

**Comment by fasaxc** [comment]
@ligc As I mentioned on slack, PPC isn't currently a platform that the Calico team support.  It'd be great if you could connect me with the team that are making these PPC builds (is that your team?) so that we can see if we can work something out.

Apart from that, kernel panics generally imply bugs in the kernel rather than the app that is using it.  Have you reported this upstream to the kernel developers?

**Comment by ligc** [comment]
We updated to Calico 2.2.0 release, and then not seeing issue any more, closing this issue.

**Comment by juliemathew** [comment]
We moved to ICpv1.2.0 on Power environment, and launched multiple clusters successfully. 
Today an issue was reported on one of the clusters that it is not accessible. We found that the master node and one of the workers went to shutoff state. Checked logs- it shows kernel panic errors (kernel panic - not syncing: fatal exception).

Images used:
docker images | grep calico
ppc64le/calico-cni v1.8.3 f3c4cd154a64 2 months ago 214 MB
ppc64le/calico-ctl v1.2.1 23f9963f0dd1 2 months ago 188 MB
ppc64le/calico-node v1.2.1 d29dd537833b 2 months ago 409 MB
ppc64le/calico-policy-controller v0.6.0 c280084af9f7 2 months ago 658 MB

Ubuntu 16.04.2 LTS cluster-1500560238580-master hvc0
cluster-1500560238580-master login: [40699.381695] Unable to handle kernel paging request for data at address 0xffffffff00000000
[40699.381791] Faulting instruction address: 0xc0000000002b35f4
[40699.381837] Oops: Kernel access of bad area, sig: 11 [#1]
[40699.381873] SMP NR_CPUS=2048 NUMA pSeries
[40699.381916] Modules linked in: xt_recent xt_set xt_multiport iptable_raw ip_set_hash_ip ip_set_hash_net ip_set ipip tunnel4 ip_tunnel nf_conntrack_netlink nfnetlink ipt_REJECT nf_reject_ipv4 xt_nat xt_tcpudp xt_comment xt_mark ipt_MASQUERADE nf_nat_masquerade_ipv4 xfrm_user xfrm_algo iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables xt_conntrack x_tables nf_nat nf_conntrack br_netfilter bridge stp llc aufs isofs vmx_crypto joydev input_leds ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear hid_generic usbhid hid ibmvscsi
[40699.382698] **CPU: 1 PID: 18744 Comm: calico-felix Not tainted** 4.4.0-83-generic #106-Ubuntu
[40699.382787] task: c0000001523e2a20 ti: c0000000ff414000 task.ti: c0000000ff414000
[40699.382857] NIP: c0000000002b35f4 LR: c0000000002b36c4 CTR: c000000000009458
[40699.382911] REGS: c0000000ff4179e0 TRAP: 0300   Not tainted  (4.4.0-83-generic)
[40699.382978] MSR: 8000000000009033 <SF,EE,ME,IR,DR,RI,LE>  CR: 24422808  XER: 00000000
[40699.383107] CFAR: 000000000007d494 DAR: ffffffff00000000 DSISR: 40000000 SOFTE: 1 
GPR00: c0000000002b36c4 c0000000ff417c60 c0000000015f7f00 0000000000000000 
GPR04: 00000000026000c0 ffffffffffffffff 00000000002dca11 c0000001ffe9ff00 
GPR08: 00000001feed0000 ffffffff00000000 0000000000000000 0000000000000c01 
GPR12: 0000000000002200 c00000000fb40980 c0000001fb0d2a20 0000000000000020 
GPR16: 000000000000006b 0000000000000011 0000000000000039 0000000000000008 
GPR20: 0000000000000010 0000000000000001 c0000001523e2a20 0000000000000000 
GPR24: 0000000000000001 c00000000178ae80 c0000001fe01f100 c0000000000b67c0 
GPR28: ffffffffffffffff 00000000026000c0 0000000000000000 c0000001fe01f100 
[40699.383874] NIP [c0000000002b35f4] kmem_cache_alloc_node+0x124/0x360
[40699.383920] LR [c0000000002b36c4] kmem_cache_alloc_node+0x1f4/0x360
[40699.383964] Call Trace:
[40699.383984] [c0000000ff417c60] [c0000000002b36c4] kmem_cache_alloc_node+0x1f4/0x360 (unreliable)
[40699.384057] [c0000000ff417cc0] [c0000000000b67c0] copy_process.isra.5+0x250/0x18a0
[40699.384120] [c0000000ff417da0] [c0000000000b7fe8] _do_fork+0xa8/0x4b0
[40699.384174] [c0000000ff417e30] [c000000000009460] ppc_clone+0x8/0xc
[40699.384228] Instruction dump:
[40699.384256] 81810008 eb21ffc8 eb41ffd0 7c0803a6 eb61ffd8 eb81ffe0 7d908120 eba1ffe8 
[40699.384351] ebc1fff0 ebe1fff8 4e800020 e95f0022 <7f29502a> 39400000 88ad02ca 994d02ca 
[40699.386325] ---[ end trace b33d4caa6bde009a ]---
[40699.388656] 
[40701.388713] Kernel panic - not syncing: Fatal exception

**Comment by ligc** [comment]
We are seeing this issue again, Julie Mathew and David Wilder could work with the community to look at the POWER calico build env .

**Comment by juliemathew** [comment]
@fasaxc as you mentioned earlier, could you please help to review the Power calico build env. 
David (wilder@us.ibm.com) can share the env details with you.. thanks for your support.

**Comment by caseydavenport** [comment]
Going to close this due to inactivity and the fact that ppc isn't supported by the Calico team.
