### ISSUE TITLE
Memory leak in KDD via http2.readLoop()

### ISSUE THREAD

**Issue by ijumps** [projectcalico/felix#1455]
Hi, I use canal as kubernetes network plugin, which use felix. I notice some abnormally memory usage for canal:

```
[root@c1~]# kubectl top pod -n kube-system | grep canal
canal-pt67l                                           75m          2811Mi          
canal-hbfbw                                           78m          3101Mi          
canal-p79mg                                           54m          3116Mi          
canal-s09m7                                           64m          1942Mi          
canal-8rd4p                                           53m          2766Mi 
```
I checked and found out calico-felix used most of the memory. Memory usage for canal-hbfbw:

```
[root@c3v129 ~]# ps aux | grep calico
root      6941  4.5 41.8 3681268 3354264 ?     Sl   Apr30 727:30 calico-felix
```

The cluster is about 1000 pods and 100 nodes, without any networkpolicy.

calico-felix version:

```
# calico-felix --version
Version:            2.2.0-rc1-2-g9d63cf6
Full git commit ID: 9d63cf651f3d033d00bf79cb967286e65a54b971
Build date:         2017-04-14T04:07:10+0000
```
( Note: This is a custom build, the only change is replace libcalico-go vendor with this PR: https://github.com/projectcalico/libcalico-go/pull/390 )

---

After talked with @fasaxc on slack, I do some test with the new feature to help diagnose memory leaks by the following steps:

1. choose a node that run canal
2. exec into container and add `export FELIX_USAGEREPORTINGENABLED=true` and `export FELIX_DEBUGMEMORYPROFILEPATH=/tmp/mem.pprof` to `/etc/service/enabled/felix/run` to enable the feature
3. kill the calico-felix process
4. run `kill -s USR1 {pid}` and save the mem.pprof file

Also, I choose another node and replace the calico-felix binary in container with an official release felix version from `calico/node:v1.2.0-rc2`, which include felix version `2.2.0`, and do the test above.

official calico-felix version:

```
# calico-felix --version
Version:            2.2.0
Full git commit ID: bc4d54dbe047c513c9a47ad5c89ff29be1128a2c
Build date:         2017-05-09T17:22:17+0000
```

Result:

**version 2.2.0-rc1-2-g9d63cf6**

![profile001](https://cloud.githubusercontent.com/assets/6194755/25931122/f235c890-363c-11e7-86b4-d18045fe95f6.png)
![profile002](https://cloud.githubusercontent.com/assets/6194755/25931123/f23af9f0-363c-11e7-873f-87849a21e33c.png)
![profile003](https://cloud.githubusercontent.com/assets/6194755/25931124/f23c67fe-363c-11e7-9b29-481c0f480904.png)

**version 2.2.0**
![profile001](https://cloud.githubusercontent.com/assets/6194755/25931144/16c86212-363d-11e7-86e2-282bdebce17e.png)
![profile002](https://cloud.githubusercontent.com/assets/6194755/25931145/16cc4b16-363d-11e7-865c-0fd0bd95a184.png)

svg file can find here:

[2.2.0-rc1-2-g9d63cf6.zip](https://github.com/projectcalico/felix/files/991823/2.2.0-rc1-2-g9d63cf6.zip)
[2.2.0.zip](https://github.com/projectcalico/felix/files/991824/2.2.0.zip)

---

This seems a memory leak on `http2.readLoop` ?

**Comment by fasaxc** [comment]
@ijumps Thanks for doing all this digging.  Certainly looks like a leak in `http2.readLoop()`.

**Comment by fasaxc** [comment]
Since the leak appears to be in the KDD, I've moved this over to the libcalico-go repo, lets continue the discussion there.

**Comment by caseydavenport** [comment]
I've built an image of Felix that includes the libcalico fix and pushed it to `caseydavenport/felix:fix-mem-leak`.

I haven't had a chance to test yet.

**Comment by ijumps** [comment]
Some more `mem.pprof`  information for version `2.2.0-rc1-2-g9d63cf6` and `2.2.0`

**2.2.0-rc1-2-g9d63cf6**

![image](https://cloud.githubusercontent.com/assets/6194755/26027084/d1a83cf8-3839-11e7-8828-9f06bba9973b.png)

**2.2.0** 

![image](https://cloud.githubusercontent.com/assets/6194755/26027095/004f4c90-383a-11e7-8095-11eb5a3f6070.png)

---

And I have started new test on version `2.2.1-6-g9c92a962`,  which is copy from calico/felix. I check the commit history, this commit version should have the fix code.

```
/ # calico-felix --version
Version:            2.2.1-6-g9c92a962
Full git commit ID: 9c92a9624d11d2ed68484d488c42a0b0d67d88aa
Build date:         2017-05-13T08:05:39+0000
```

And some init data for this version:

**just start**
![image](https://cloud.githubusercontent.com/assets/6194755/26027138/dd0ef3ec-383a-11e7-9c6c-f882083eb7ad.png)

**4 hours later**

![image](https://cloud.githubusercontent.com/assets/6194755/26027145/f55b59f4-383a-11e7-89e0-6af3e071dcee.png)

---

I will update this a few days later, willing to see this is fixed.

@fasaxc @caseydavenport

**Comment by ijumps** [comment]
**1 day later**

![image](https://cloud.githubusercontent.com/assets/6194755/26035793/b4d0b8aa-3904-11e7-90cf-11ee0d88e65e.png)

**Comment by fasaxc** [comment]
@ijumps It's certainly looking a lot better.  Please can you keep an eye on the `makeSlice` value for a few days, that has crept up from 500kb to 1500mb over a day.  Would be great to know if that keeps increasing.

**Comment by fasaxc** [comment]
Fixed by #1457

**Comment by ijumps** [comment]
**2 days later**

![image](https://cloud.githubusercontent.com/assets/6194755/26116573/3306a562-3a96-11e7-90b6-e29e86fec918.png)

**3 days later**

![image](https://cloud.githubusercontent.com/assets/6194755/26116635/6bd452e0-3a96-11e7-86bc-424b14123904.png)

---

@fasaxc memory seems still increase but very slow, `makeSlice` still increase.

I'd like to use this version, and looking forward the new release for calico/node

**Comment by fasaxc** [comment]
@ijumps Just to make sure I'm 100% clear.  The new version is a lot better, right?  IIUC, we've reduced the leak rate from ~100MB/day to ~0.5MB/day?

**Comment by ijumps** [comment]
@fasaxc  Yes, the new version is a lot better for memory usage (this is what I tested). A reduce from >100MB/day (2.2.0-rc1-2-g9d63cf6), ~50MB/day (2.2.0)  to <1MB/day (2.2.1-6-g9c92a962).

**Comment by ijumps** [comment]
**4 days later**

![image](https://cloud.githubusercontent.com/assets/6194755/26284903/f98124a8-3e77-11e7-8679-9a12fd022e93.png)

**5 days later**

![image](https://cloud.githubusercontent.com/assets/6194755/26284904/01bb88e8-3e78-11e7-811a-214db2d0c51b.png)

**one week later**

![image](https://cloud.githubusercontent.com/assets/6194755/26284906/0a33fd02-3e78-11e7-86d8-06d102953e75.png)

I notice `crypto/tls(*block).reserve` took a lot memory, this may help to find the potential memory leak.

I will use the new release version from now on, and I will keep this update when I have time.

**Comment by fasaxc** [comment]
Thanks for the update @ijumps, that should give us enough to go on.

Just to record the previous fix: the problem wasn't a leak in readLoop, it was actually that we were leaking kubernetes API watchers each time we did a resync with kubernetes.  Each watcher was backed by a HTTP2 connection with its own readLoop.

My next step would be to try to gather more diagnostics, for example, by hacking the cod ethat starts a read loop to print out a stack trace so we can see where they're getting created.

**Comment by fasaxc** [comment]
Closing since any remaining leak is very slow (any may be explained by buffer pool based allocation).  @ijumps Please feel free to open a new issue to track the small memory leak if you've got more evidence to help track it down.
