### ISSUE TITLE
Tell iptables-restore to use its lock if available

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1470]
Recently, iptables-restore has been updated to support the xtables lock, which prevents concurrent access to iptables os that different users can avoid clobberring each others updates.  We should add support for the lock and turn it on when available.

- [x] Figure out what settings kube-proxy uses (I think there are multiple options for the lock now)
- [x] Add support for setting the flag
- [ ] ~~Detect support (version check or trial call?)~~
- [ ] Update container image to make it easy to mount in the relevant files (lock is file-based so we need to share the file).
- [ ] Make iptables retry/resync less aggressive since it won't be needed to avoid kube-proxy conflicts.

**Comment by fasaxc** [comment]
Hmm, the iptables-restore locking function hasn't landed yet.  `kube-proxy` re-implements the iptables-restore lock itself: https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/iptables.go#L360

**Comment by caseydavenport** [comment]
@fasaxc I think this is done now?

**Comment by fasaxc** [comment]
@caseydavenport Kind-of.  We hit some issues so it's off-by-default. #1504
