### ISSUE TITLE
TCP SYN retries persistently dropped but new TCP conn gets through

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1490]
@gunjan5 saw this on a k8s e2e run: test container opens a TCP connection before Felix has finished programming iptables.  The packets are (correctly) dropped, then Felix finishes the programming, instead of packets now flowing, we see them continue to be dropped.  However, a new TCP connection does succeed.

We've seen similar issues with pings, where a failed ping process consistently fails but a newly launched ping succeeds.

Appears there's some caching going on somewhere, possibly in conntrack or the routing cache.

## Expected Behavior
After Felix programs the dataplane, the SYN retries should get through.

## Current Behavior
SYN retries persistently fail, even after 20+ seconds.

## Your Environment
* `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.7
* Operating System and version:

**Comment by fasaxc** [comment]
Doing some investigation of why we can get persistently-failing TCP connections from a pod and yet a new TCP connection works fine.  I hit one repro when I was first setting up my repro scenario where I misconfigured my k8s service so that there were no matching pods:

- packet misses the NAT rules because there’s no dest to NAT to
- packet gets an “unreplied” non-NATted conntrack entry
- packet flows onto the GCE network due to default gateway and gets dropped (I think)
- fixing the service leaves the above connection broken because NAT is done at conntrack-creation time only
- connection times out (after connection timeout >1 min for `wget`)

Interestingly, there’s a kube-proxy iptables rule that looks like it’s meant to fix this case: `-A KUBE-SERVICES -d 10.102.151.4/32 -p tcp -m comment --comment "default/nginx: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable`  However, that rule is only linked from the OUTPUT chain, which these packets don’t hit when using Calico.  (They may hit the OUTPUT chain when a bridge is involved, I haven’t checked yet.)  CC @casey @gunjan5 @alexp (edited)

To Calico, those packets look like they’re just passing through; Calico doesn’t know that they should have been destined for a service.  (We don’t hit any drop rules or anything.) (edited)

Guess I’ll spin up a vanilla k8s system to compare with a bridged solution.  If that hits the above rule then I guess this is a kube-proxy + routed network bug.

**Comment by gunjan5** [comment]
@fasaxc did you mean to CC @caseydavenport and @lxpollitt ? :) 

I'm attaching the pcap. The flow of interest is the one with `ip.src == 10.8.6.53 && ip.dst == 10.11.252.56` 
![image](https://user-images.githubusercontent.com/5966968/27884986-27e18096-618b-11e7-87b7-a707e09302ab.png)

it's with 2 retries both with 100 second timeout, the second one goes through right away.

[cappyMcCapface1111.pcap.zip](https://github.com/projectcalico/felix/files/1126030/cappyMcCapface1111.pcap.zip)

**Comment by fasaxc** [comment]
Oops, was copy-pasting my slack comments, forgot to remove the incorrect `@`s

**Comment by fasaxc** [comment]
The problem repros on vanilla k8s with no Calico too (spun up a 2-node rig with GKE, running k8s 1.6.6).

**Comment by fasaxc** [comment]
I failed to repro by pausing/unpausing Felix to simulate a slow endpoint programming:

- create nginx server pod behind a service
- check connectivity to nginx form a new busybox pod
- send all felix instances a SIGSTOP to pause them
- create new busybox pod and run `wget nginx` -- packets get dropped so wget seems to hang
- unpause felix instances on all nodes
- *same* wget process now succeeds in connecting to nginx.

**Comment by fasaxc** [comment]
Trying policy:
- create nginx server pod behind a service
- check connectivity to nginx form a new busybox pod
- add policy to nginx pod that denies traffic
- start new busybox pod
- start `wget nginx`, `wget` seems to hang as expected
- delete deny policy and add an allow policy
- *same* wget instance succeeds in connecting to nginx.

**Comment by fasaxc** [comment]
Tried the SIGSTOP/CONT test again, this time, checking that the felix I was continuing was the one on the same host as the the busybox pod.  Again, wget managed to connect once I sent the SIGCONT.

**Comment by fasaxc** [comment]
@gunjan5 Do you think the issue you hit could have been down to slow kube-proxy programming?  The only way I've been able to repro this so far is when my traffic starts before the NAT rule is in place, meaning that subsequent packets bypass NAT.

**Comment by gunjan5** [comment]
@fasaxc here are the conntrack logs:

```
    [NEW] udp      17 30 src=10.8.6.97 dst=10.11.240.10 sport=39159 dport=53 [UNREPLIED] src=10.8.6.2 dst=10.8.6.97 sport=53 dport=39159
 [UPDATE] udp      17 30 src=10.8.6.97 dst=10.11.240.10 sport=39159 dport=53 src=10.8.6.2 dst=10.8.6.97 sport=53 dport=39159
 [UPDATE] udp      17 180 src=10.8.6.97 dst=10.11.240.10 sport=39159 dport=53 src=10.8.6.2 dst=10.8.6.97 sport=53 dport=39159 [ASSURED]
    [NEW] udp      17 30 src=10.8.6.97 dst=10.11.240.10 sport=45307 dport=53 [UNREPLIED] src=10.8.6.2 dst=10.8.6.97 sport=53 dport=45307
 [UPDATE] udp      17 29 src=10.8.6.97 dst=10.11.240.10 sport=45307 dport=53 src=10.8.6.2 dst=10.8.6.97 sport=53 dport=45307
 [UPDATE] udp      17 180 src=10.8.6.97 dst=10.11.240.10 sport=45307 dport=53 src=10.8.6.2 dst=10.8.6.97 sport=53 dport=45307 [ASSURED]
    [NEW] tcp      6 120 SYN_SENT src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 [UNREPLIED] src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128
 [UPDATE] tcp      6 60 SYN_RECV src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128
 [UPDATE] tcp      6 86400 ESTABLISHED src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128 [ASSURED]
 [UPDATE] tcp      6 120 FIN_WAIT src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128 [ASSURED]
 [UPDATE] tcp      6 30 LAST_ACK src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128 [ASSURED]
 [UPDATE] tcp      6 120 TIME_WAIT src=10.8.6.97 dst=10.11.249.108 sport=46128 dport=80 src=10.8.6.96 dst=10.8.6.97 sport=80 dport=46128 [ASSURED]
```

`10.8.6.97` - client pod
`10.8.6.96` - server pod
`10.11.249.108` - service IP
`10.11.240.10` - kube-DNS

all this was on one node.

I'm attaching full packet capture and full conntrack logs 

[cappyMcPcapface222.pcap.zip](https://github.com/projectcalico/felix/files/1129338/cappyMcPcapface222.pcap.zip)
[conntrack_logs.zip](https://github.com/projectcalico/felix/files/1129339/conntrack_logs.zip)

Let me know if you want access to my cluster, I have a custom built e2es that take different timeout and retry settings based on ENV var to hit this issue with different config without rebuilding them.

**Comment by fasaxc** [comment]
@gunjan5 Are you sure those logs came from a repro?  The conntrack logs above look like the connection "just worked".  We see it transition into "assured" state, meaning there has been traffic in both directions and then FIN_WAIT and LAST_ACK indicating (IIUC) a graceful shutdown of the connection.  The trace above definitely did get DNATted to the server pod IP.

**Comment by fasaxc** [comment]
Ah, looking in your logfile I also see this unreplied flow, which didn't get NATted as it should have (so it got blackholed):
```
    [NEW] tcp      6 120 SYN_SENT src=10.8.6.97 dst=10.11.249.108 sport=45914 dport=80 [UNREPLIED] src=10.11.249.108 dst=10.8.6.97 sport=80 dport=45914
[DESTROY] tcp      6 src=10.8.6.97 dst=10.11.249.108 sport=45914 dport=80 [UNREPLIED] src=10.11.249.108 dst=10.8.6.97 sport=80 dport=45914
```

Two possibilities:

- NAT rule wasn't put in place in time by kube-proxy
- NAT rule was put in place but someone else (e.g Felix) clobbered it.  I think this is unlikely since we probably aren't doing any NAt table update in this scenario?

**Comment by fasaxc** [comment]
We could also try with the iptables lock fix in place to see if that fixes it.

**Comment by gunjan5** [comment]
I had a few more runs and got the same results:
```
    [NEW] tcp      6 120 SYN_SENT src=10.8.6.100 dst=10.11.245.166 sport=48274 dport=80 [UNREPLIED] src=10.11.245.166 dst=10.8.6.100 sport=80 dport=48274
[DESTROY] tcp      6 src=10.8.6.100 dst=10.11.245.166 sport=48274 dport=80 [UNREPLIED] src=10.11.245.166 dst=10.8.6.100 sport=80 dport=4827
```

Then I had a bunch of runs with the lock file image and `/run` mounted to the calico-node pod, but I didn't see any difference:
```
[1499903943.195079]	    [NEW] tcp      6 120 SYN_SENT src=10.8.6.106 dst=10.11.241.185 sport=49182 dport=80 [UNREPLIED] src=10.11.241.185 dst=10.8.6.106 sport=80 dport=49182
[1499903954.949795]	[DESTROY] tcp      6 src=10.8.6.106 dst=10.11.241.185 sport=49182 dport=80 [UNREPLIED] src=10.11.241.185 dst=10.8.6.106 sport=80 dport=49182
```
> Note: 1499903943.195079 = 23:59:03.195 and 
> 1499903954.949795 = 23:59:14.949  as I set the connection timeput to 10 seconds

kube-proxy logs suggest the service port was added 3 seconds before the `SYN_SENT` conntrack entry.
```
I0712 23:59:00.274026       8 proxier.go:309] Adding new service port "e2e-tests-network-policy-zvxqw/svc-server:server-80" at 10.11.241.185:80/TCP
```

**Comment by fasaxc** [comment]
@gunjan5 Does `kube-proxy` log when it adds an endpoint to the service?  The key factor is whether there are any endpoints backing the service.  If not, `kube-proxy` will render a chain with no load balancing rules so the packet ends up creating a bad conntrack flow.

**Comment by caseydavenport** [comment]
Have we tracked this down to a kube-proxy issue? Can we close this?

**Comment by caseydavenport** [comment]
@fasaxc @gunjan5 ^

**Comment by gunjan5** [comment]
I still have to repro this and get kube-proxy debug logs to confirm the issue, but have been busy with other stuff lately.

**Comment by caseydavenport** [comment]
>The problem repros on vanilla k8s with no Calico too (spun up a 2-node rig with GKE, running k8s 1.6.6).

I'm going to close this since it seems to be unrelated to Calico.
