### ISSUE TITLE
Poor dataplane apply performance with many conntrack entries

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1501]
@doublek did some testing with a heavily-loaded conntrack table; found that Felix was taking a long time to apply updates if it happened to do a conntrack deletion as part of the update.

Analysing the cause:

- we shell out to conntrack to do the deletions
- conntrack is implemented as a linear scan through the table, which is slow
- our shell-out was on the critical path.

**Comment by caseydavenport** [comment]
Has this been fixed by #1498 + #1500?

**Comment by fasaxc** [comment]
Yes, as best we can.
