### ISSUE TITLE
Update default MTU for Ip-in-Ip as 1430

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/felix#1532]
Based on https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_openstack_platform/7/html/networking_guide/sec-mtu, in Openstack with vxlan environment, the default MTU is 1450 which is even less than GCE 1460, so the default MTU for the IP-in-IP should be update to 1430.

The proposal is adding a new line for `OpenStack VXLAN` and set the default MTU for Ip-in-Ip as 1430.

**Comment by tmjd** [comment]
@gyliu513 In general, I don't believe it is necessary to use IP-in-IP when running on OpenStack.  Have you attempted to disable source/destination IP checks in OpenStack and then turn off IP-in-IP?  If you are able to do that then you don't need to use the tunnel which this setting is for.

**Comment by gyliu513** [comment]
@tmjd can you please show more detail for how to disable the source/destination IP checks in OpenStack?

**Comment by tmjd** [comment]
@kprabhak Could you help with this? I think the source/destination IP check needs disabling, but not 100% sure about that.

**Comment by kprabhak** [comment]
In OpenStack, this would be by disabling Port Security on the port to the instance, as described here:
https://wiki.openstack.org/wiki/Neutron/ML2PortSecurityExtensionDriver

Your OpenStack deployment would need to have the Port Security ML2 extension enabled. Also Port security is currently mutually exclusive with security groups, so you wouldn't be using a security group for the VM (and therefore you would want to ensure that you have tight Calico policy protection for your K8s pods (and potentially also for the host instance within your VM).

An alternate approach of course is to just use IP-in-IP mode as you've discussed above.

**Comment by gyliu513** [comment]
Thanks, but the problem is that we cannot guarantee all of the OpenStack cluster have such configurations, so updating the MTU to 1430 would be a good option. @kprabhak

**Comment by caseydavenport** [comment]
Closing - I don't think we can reasonably support a default value for all MTUs, and we have another issue open for auto-detection support which I believe is the correct path forward. For now, we have documentation on how to configure MTU as needed based on environment.
