### ISSUE TITLE
k8sfv tests failing since 30th Aug

### ISSUE THREAD

**Issue by lwr20** [projectcalico/felix#1547]
## Expected Behavior
Tests should all pass

## Current Behavior
The following tests have been failing since 30th August:
* Felix/KDD FV tests.calculation graph scale test with a local host should see health readiness endpoint (from (junit.xml))
* Felix/KDD FV tests.with a k8s clientset with 1 remote node should not leak memory [slow] (from (junit.xml))

The first one fails every time, the second fails about half the time.

Stacktrace for the first:
```
/go/src/github.com/projectcalico/felix/k8sfv/calc_graph_test.go:77
Timed out after 20.000s.
Expected
    <int>: 503
to be ==
    <int>: 204
/go/src/github.com/projectcalico/felix/k8sfv/calc_graph_test.go:76
```
For the second it appears that memory per-run is increasing by around 2%.  Since the threshold is set at 2%, we get intermittent failures.

Full run output in Jenkins at http://localhost:8080/job/k8sfv/159/console

## Possible Solution
@fasaxc suggested it might be CRD related? 

## Steps to Reproduce (for bugs)
Run the k8sfv tests.

**Comment by lwr20** [comment]
Weirdly, this test does seem to be one of the ones we run at check-in time on Semaphore - and it passes...

**Comment by fasaxc** [comment]
Hmm, or an interaction between multiple tests

**Comment by fasaxc** [comment]
No failures since I fixed the version of Typha in use.
