### ISSUE TITLE
Felix docker image incorrectly activates "OpenStack special mode" 

### ISSUE THREAD

**Issue by Dirbaio** [projectcalico/felix#1554]
## Expected Behavior
"OpenStack" mode is not enabled by default when using the Felix docker image

## Current Behavior
"OpenStack" mode gets enabled by default

## Cause

The config checks for OpenStack mode by seeing if the metadata addr is set to non-default: https://github.com/projectcalico/felix/blob/4b79218b14c5fc0c95d5abc0810d781172597063/config/config_params.go#L223

But felix.cfg sets it to None: https://github.com/projectcalico/felix/blob/4b79218b14c5fc0c95d5abc0810d781172597063/docker-image/felix.cfg#L2

which causes that check to trigger.

## Steps to Reproduce (for bugs)
Run the `felix` docker image with debug log level, you will see this in the logs
```
2017-09-18 21:51:18.552 [DEBUG][7] config_params.go 224: OpenStack metadata IP set to non-default, assuming OpenStack active
```

**Comment by fasaxc** [comment]
Thanks for the report @Dirbaio. That definitely looks like a bug.
