### ISSUE TITLE
Does not calicoctl support validate yaml format?

### ISSUE THREAD

**Issue by hiro-noguchi** [projectcalico/felix#1606]
Hi, calico experts.
I am testing calico HostProtection.

## Expected Behavior

If policy yaml need to specify protocol, calicoctl should outputs validation error.

## Current Behavior

I created profile for hostendpoint via calicoctl.

```bash
$ cat Profile.yaml
apiVersion: v1
kind: profile
metadata:
  name: Profile
  labels:
    profile: Profile
spec:
  ingress:
  - action: allow
    icmp:
      type: 8
    source:
      nets:
      - 192.168.122.10/32
  - action: deny
    source:
  egress:
  - action: allow

$ calicoctl create -f Profile.yaml
Successfully created 1 'profile' resource(s)
```

I created hostendpoint via calicoctl.

```bash
$ cat HostProtection.yaml
- apiVersion: v1
  kind: hostEndpoint
  metadata:
    name: enp0s3
    node: HostProtection
    labels:
      role: webserver
      environment: production
  spec:
    interfaceName: enp0s3
    profiles: [Profile]
    expectedIPs: ["192.168.122.6"]

$ calicoctl create -f HostProtection.yaml
Successfully created 1 'hostEndpoint' resource(s)
```

Then i got felix error below:

```
ov 07 11:32:16 HostProtection calico-felix[1258]: ERROR table.go 778: Failed to program iptables, loading diags before panic. error=exit status 1 ipVersion=0x4 table="filter"
Nov 07 11:32:16 HostProtection calico-felix[1258]: ERROR table.go 784: Current state of iptables ipVersion=0x4 iptablesState="# Generated by iptables-save v1.6.0 on Tue Nov  7 11
Nov 07 11:32:16 HostProtection calico-felix[1258]: PANIC table.go 786: Failed to program iptables, giving up after retries error=exit status 1 ipVersion=0x4 table="filter"
Nov 07 11:32:16 HostProtection systemd[1]: calico-felix.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 07 11:32:16 HostProtection systemd[1]: calico-felix.service: Unit entered failed state.
Nov 07 11:32:16 HostProtection systemd[1]: calico-felix.service: Failed with result 'exit-code'.
Nov 07 11:32:16 HostProtection systemd[1]: calico-felix.service: Service hold-off time over, scheduling restart.
Nov 07 11:32:16 HostProtection systemd[1]: Stopped Calico Felix agent.
Nov 07 11:32:16 HostProtection systemd[1]: calico-felix.service: Start request repeated too quickly.
Nov 07 11:32:16 HostProtection systemd[1]: Failed to start Calico Felix agent.
```

Calico felix agent cannot restart again.

Incidentally, when i tested yaml format below, it succeded:

```bash
cat Profile.yaml
apiVersion: v1
kind: profile
metadata:
  name: Profile
  labels:
    profile: Profile
spec:
  ingress:
  - action: allow
    protocol: icmp
    icmp:
      type: 8
    source:
      nets:
      - 192.168.122.10/32
  - action: deny
    source:
  egress:
  - action: allow
```

## Possible Solution

I think profile need protocol key in ingress policy list. Or it should validate yaml format. Is this bug?

## Your Environment

calico-felix version: 2.5
calicoctl version: 1.6.1
etcd version: 2.2.5
OS: ubuntu 16.04
Orchestrator: OpenStack Ocata

calico-felix version in protected host:2.4

```
+------------+  +-----------+  +-----------+
| OpenStack  |  | OpenStack |  | OpenStack |
| Controller |  | Compute1  |  | Compute2  |
| + etcd     |  +-----+-----+  +-----+-----+
+-----+------+        |              |
      |               |              |
------+---------------+--------------+----- 192.168.122.0/24
              |
      +-------+--------+
      | HostProtection |
      | Node           |
      +----------------+
```

**Comment by fasaxc** [comment]
@hiro-noguchi Thanks for the bug report.  Yes, that field should be validated(or defaulted by calicoctl).  I have moved the report to the libcalico-go repo, which is where the validation logic lives: https://github.com/projectcalico/libcalico-go/issues/657

**Comment by hiro-noguchi** [comment]
@fasaxc Thank you very much for your prompt reply.

**Comment by ozdanborne** [comment]
@fasaxc In addition to patching libaclico-go so that invalid ICMP rules don't pass validation, do we also want to patch felix so that it doesn't critically fail when an invalid rule does make it into the datastore?

**Comment by fasaxc** [comment]
@ozdanborne Felix uses the validator to vet the data it reads and it drops any resources that don't pass validation.  If we fix validation in libcalico-go then that should naturally fix Felix too once we rev libcalico-go there.

**Comment by fasaxc** [comment]
That said, if the data is fairly unambiguous, it's an option to make Felix "just handle it" instead of validating it away.  In this case, we could do that by saying "if a rule has an ICMP struct in it and no protocol specified, default the protocol to ICMP".
