### ISSUE TITLE
Versions output is weird

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1617]
```
$ docker exec -ti fcfe69bf3ba2 versions
confd v1.0.0-alpha1-12-g2933b6f
BIRD version 1.6.3
libnetwork-plugin: v1.1.0-28-g20f511e
calico-bgp-daemon: v0.2.2

Felix:
2017-11-09 23:23:54.080 [INFO][243] logutils.go 83: Early screen log level set to debug
2017-11-09 23:23:54.080 [DEBUG][243] felix.go 125: No GOGC value set, defaulting to 20%.
Version:            3.0.0-alpha1-37-gb541e9a7
Full git commit ID: b541e9a79e5d5c9d713fa8304914637fc245ba91
Build date:         2017-11-09T23:11:09+0000
```

Note these lines:

> 2017-11-09 23:23:54.080 [INFO][243] logutils.go 83: Early screen log level set to debug
2017-11-09 23:23:54.080 [DEBUG][243] felix.go 125: No GOGC value set, defaulting to 20%.

## Expected Behavior

Should not emit logging when running versions.

## Current Behavior

Emits logging when running versions.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by fasaxc** [comment]
> Early screen log level set to debug

means you've got FELIX_LOGSEVERITYSCREEN=debug (or FELIX_EARLYLOGSEVERITYSCREEN=debug).  Using the environment variable triggers special early logging set-up so that we can diagnose problems in argument and config parsing.

Still may want to address this for the version command but, in a sense, you asked for debug output, and that's what you got :-)

**Comment by bcreane** [comment]
closing via @caseydavenport suggestion
