### ISSUE TITLE
calico-felix binds healthcheck to all interfaces

### ISSUE THREAD

**Issue by tuminoid** [projectcalico/felix#1639]
## Expected Behavior
In Kubernetes, Felix healthcheck port is not bound to all interfaces, only to localhost.

## Current Behavior

Felix healthcheck port 9099 is bound to all interfaces, and is exposed to the world, and must be secured by firewall or iptables rules.

## Possible Solution

Bind healthcheck port to localhost, or allow configuration option to do so.

## Steps to Reproduce (for bugs)

1. Run calico in kubernetes, run nmap to check for open ports from another host.
2. Port 9099 is open to the world.

## Context

Felix healthcheck port is open and exposed, and provides additional attack vector for hacking the cluster.

## Your Environment
* calico/node 2.5.0
* Kubernetes 1.7.4
* Etcd version 3.2.7
* Operating System and version: RHEL 7.4

**Comment by tuminoid** [comment]
For example, with `ab -n 1000000 -c 10000 IP:9099/liveness` you can trigger DoS against `/liveness` and cause calico-node to get restarted for missing probes. On my cluster, the limit seems to be around 8000 requests/s.

**Comment by caseydavenport** [comment]
This is fixed in master as of https://github.com/projectcalico/felix/pull/1782 and will be released in v3.2.0. Thanks!

**Comment by tuminoid** [comment]
Awesome, thank you :+1:
