### ISSUE TITLE
calico for windows cantainer

### ISSUE THREAD

**Issue by wangxinxu411** [projectcalico/felix#1721]
Hello guys, I wonder if windows container support calico to be 3rd-party overlay plugin? i found that felix can run on windows server,however...when i use calicoctl get node, the put out did not contain the windows node.  i did not find the instruction of how to run a windows container server with calico either in calico documents or windows container documents.did i miss something??pls feedme back .THX

**Comment by ahrkrak** [comment]
Windows policy support is still in development and we don't have any documentation yet. You will need to deploy with Kubernetes for node configuration. It should work with other overlays like flannel.

**Comment by pablodav** [comment]
There is an announcement about some support coming: 

https://cloudblogs.microsoft.com/windowsserver/2017/12/07/securing-modernized-apps-and-simplified-networking-on-windows-with-calico/

But haven't found yet howto deploy calico on windows node.

**Comment by ylhyh** [comment]
Any update about supporting Windows container?

**Comment by fasaxc** [comment]
Felix has been ported to Windows (with some limitations) https://github.com/nwoodmsft/SDN/blob/docs/Calico/CalicoFelix.md

**Comment by ducttapecoder-vt** [comment]
Microsoft announced "upcoming availability of Tigera Calico for Windows" in September 2018: https://techcommunity.microsoft.com/t5/Networking-Blog/Top-10-Networking-Features-in-Windows-Server-2019-1-Container/ba-p/339791

Has there been any developments on this front or is it limited purely to 'policy only mode'? Is there expectation that a networking port of Calico will be available in the near future or is Canal the only way forward?

**Comment by fasaxc** [comment]
Tigera Calico for Windows with BGP networking and IPAM support is now available to [Tigera Essentials](https://www.tigera.io/essentials/) subscribers.

**Comment by ahrkrak** [comment]
@ducttapecoder-vt @ylhyh @pablodav @wangxinxu411  feel free to ping me via email (andy AT tigera.io) if you're interested in Calico for Windows, we'd be happy to open that conversation. As @fasaxc says, this is available to Tigera Essentials subscribers (i.e. it's not free / open source).

**Comment by ducttapecoder-vt** [comment]
@ahrkrak Are there any plans for making Calico for windows free / open source or is it forever subscription based?

**Comment by ylhyh** [comment]
Yes, can you share the information or materials for that? I have visited the link [Tigera Essentials](https://www.tigera.io/essentials/) yesterday, but didn't find releated information

**Comment by ahrkrak** [comment]
Sorry for the slow reply here. 
Agreed - the text on the Essentials page is "minimal"... it just says " Calico for Windows is exclusively available with Tigera Essentials." We need to expand that! I'm happy to get on a call to talk through what we're doing in more detail (email in earlier message).
We don't currently have plans to make Calico for Windows free/open source. We need to cover the significant additional development/maintenance costs and given that Windows users are by definition not running a full open source stack, this is a reasonable compromise to help support our core Linux open source team delivering lots of value to the community with the free Calico for Linux.
