### ISSUE TITLE
Network set CIDRs should be canonicalised

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#1735]
## Expected Behavior

When we copy CIDRs from the GlobalNetworkSet into felix's internal calculation graph, we copy from the libcalico-go IPNet to a Felix CIDR struct without masking the CIDR. libcalico-go doesn't seem to mask the CIDR either.  That could lead to mishandling of equivalent CIDRs with different representations.

## Possible Solution

- Mask the CIDR in named_port_index as we copy it into Felix's data structures.
- Mask the CIDR in the felix update processor as we copy from v3 to backend model.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Fixed by #1741
