### ISSUE TITLE
Set FELIX_IPTABLESALLOWACTION=RETURN for calico-node does not take effect

### ISSUE THREAD

**Issue by jingax10** [projectcalico/felix#1840]
By following https://docs.projectcalico.org/v2.6/reference/felix/configuration, I need to set IptablesMangleAllowAction, which is configured by FELIX_IPTABLESALLOWACTION. However, after I added FELIX_IPTABLESALLOWACTION=RETURN to cluster/addons/calico-policy-controller/calico-node-daemon.yaml for calico-node container, I still observed ACCEPT target in mangle table. For example,

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
cali-PREROUTING  all  --  anywhere             anywhere             /* cali:6gwbT8clXdHdC1b1 */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain cali-PREROUTING (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* cali:6BJqBjBC7crtA-7- */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             /* cali:nE3PUa5RSRqBBvwx */ mark match 0x1000000/0x1000000
ACCEPT     all  --  anywhere             anywhere             /* cali:qgFofvzQe6yJPouQ */
cali-from-host-endpoint  all  --  anywhere             anywhere             /* cali:o178eO5vvpj8e65z */
ACCEPT     all  --  anywhere             anywhere             /* cali:5TQcm-i_T8rVGEEa */ /* Host endpoint policy accepted packet. */ mark match 0x1000000/0x1000000

Chain cali-failsafe-in (0 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             /* cali:wWFQM43tJU7wwnFZ */ multiport dports ssh
ACCEPT     udp  --  anywhere             anywhere             /* cali:LwNV--R8MjeUYacw */ multiport dports bootpc

Chain cali-from-host-endpoint (1 references)
target     prot opt source               destination        
```

## Expected Behavior

I expect RETURN target in mangle table instead of ACCEPT as configured.

## Steps to Reproduce (for bugs)

1. added FELIX_IPTABLESALLOWACTION=RETURN to cluster/addons/calico-policy-controller/calico-node-daemon.yaml for calico-node container
2. make quick-release
3. set relevant ENVs, e.g.,
```
export KUBE_GCE_ENABLE_POLICY_ROUTING=true
export KUBE_NODE_OS_DISTRIBUTION=ubuntu
export NUM_NODES=1
export KUBE_CLUSTER_INITIALIZATION_TIMEOUT=3600
export KUBE_UP_AUTOMATIC_CLEANUP=true
export KUBE_GCE_ZONE=us-west1-a
export KUBE_GCE_ENABLE_IP_ALIASES=true
export NETWORK_POLICY_PROVIDER=calico
```
4. Run cluster/kube-up.sh on GCE.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container): 2.6.7
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver):
* Operating System and version:
* Link to your project (optional):

**Comment by jingax10** [comment]
Thanks @fasaxc! ``FELIX_IPTABLESMANGLEALLOWACTION`` works. I thereby close the issue.

p.s. It would be great to update the configuration doc as well. 

/close

**Comment by caseydavenport** [comment]
https://docs.projectcalico.org/v3.1/reference/felix/configuration

Yeah, we still reference `IPTABLESALLOWACTION` here :(

**Comment by fasaxc** [comment]
I put up a PR to fix the names.  Looks like the canonical names were correct but we forgot to update the derived env var names.

**Comment by ozdanborne** [comment]
Fixed by https://github.com/projectcalico/calico/pull/2045
