### ISSUE TITLE
Multiple felix tests failing with K8s 1.10.4

### ISSUE THREAD

**Issue by tomdee** [projectcalico/felix#1849]
Diags here https://semaphoreci.com/calico/felix-2/branches/pull-request-1848/builds/1

**Comment by tomdee** [comment]
I this is now fixed? @neiljerram

**Comment by neiljerram** [comment]
Yes, I think so; but @song-jiang was handling it, so best to double check with him.

**Comment by song-jiang** [comment]
This issue has been fixed by https://github.com/projectcalico/felix/pull/1853
