### ISSUE TITLE
why iptables rule match ! src-type LOCAL and src-type LOCAL 

### ISSUE THREAD

**Issue by gaopeiliang** [projectcalico/felix#1850]
I use calico with kubernetes in ip_ip tunnel mode, I have found an iptable rule about tunnel0 NAT,
`-A cali-POSTROUTING -o tunl0 -m comment --comment "cali:JHlpT-eSqR1TvyYm" -m addrtype ! --src-type LOCAL --limit-iface-out -m addrtype --src-type LOCAL -j MASQUERADE`

why the match ! src-type LOCAL and src-type LOCAL ? 

the rule will match ! src-type LOCAL with test,  is it an mistake about -m addrtype --src-type LOCAL , or other things I have don't know.... 

Environment:
    calico/node : v2.6.2
    etcd: 3.2
    kubernetes: 1.8

**Comment by fasaxc** [comment]
There's also a `--limit-iface-out` in the first match.  Hope that helps.
