### ISSUE TITLE
Memory leak? in felix

### ISSUE THREAD

**Issue by uthark** [projectcalico/felix#1855]
We found that container is regularly killed by OOM Killer.

## Expected Behavior

Canal-felix should not be oomkilled.

## Current Behavior

Canal-felix is regularly OOM killed.

## Context
This is how it looks like:
it slowly grows until it's memory limit and then got OOM killed. All lines are from canal-felix.

<img width="1013" alt="screenshot 2018-07-13 13 59 27" src="https://user-images.githubusercontent.com/176118/42708862-851a8356-86ac-11e8-8065-ee141e41035d.png">

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):
* And/Or, `calico/node` container version (if running Felix in a container):
quay.io/calico/node:v2.6.2
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):
Kubernetes
* Orchestrator version (if used):
1.9.x
* Etcd version (if using etcd datastore driver):
n/a
* Operating System and version:
Ubuntu 16.04 LTS

it is configured to 192mb RAM limit.

**Comment by fasaxc** [comment]
@uthark Thanks for the report.  We fixed some potential leaks in later patch releases.  Suggest you upgrade to the latest v2.6.x release and see if that fixes your problem.

**Comment by uthark** [comment]
@fasaxc Thank, will try and respond here with the findings.

**Comment by uthark** [comment]
We tried latest felix and memory usage looks much better. Thank you!
