### ISSUE TITLE
support: how to config some calico nodes as ASN655xx and other nodes as ASN650xx

### ISSUE THREAD

**Issue by peiqi-caicloud** [projectcalico/felix#1869]
Hello, 

In my situation, I deployed calico as followed: https://docs.projectcalico.org/v3.1/reference/private-cloud/l3-interconnect-fabric#the-as-per-rack-model

but I need to configure nodes in some certain ToRs as one AS, and other nodes as another AS.
how can I configure using calicoctl ...

thanks.

**Comment by fasaxc** [comment]
You can set the local AS that Calico will use on each Node using the node resource: https://docs.projectcalico.org/v3.1/reference/calicoctl/resources/node.  You can set the AS that it will expect each peer to use on the BGP peer resource https://docs.projectcalico.org/v3.1/reference/calicoctl/resources/bgppeer.
