### ISSUE TITLE
Felix should ensure IP forwarding is enabled for all endpoints

### ISSUE THREAD

**Issue by plwhite** [projectcalico/felix#187]
Forwarding must be enabled on all endpoint interfaces, or they won't work. In other words, `/proc/sys/net/ipv4/conf/<interface ID>/forwarding` should be 1 (and the same for IPv6). This is usually the default, based on `net.ipv4.ip_forward` and `net.ipv6.conf.all.forwarding` in `/etc/sysctl.conf`, but if it is not then endpoints don't work properly.

Felix should probably check the values for each tap interface, just as it sets the value of `proxy_arp` for them, so that they are guaranteed to work.

**Comment by neiljerram** [comment]
Note that setting on TAP interfaces may not be sufficient.  I would guess it's also needed on the interfaces that are involved in routing between compute hosts.

(I wonder whether the per-interface forwarding flag means 'enable forwarding from this interface' or 'enable forwarding to this interface', or perhaps both?)

**Comment by plwhite** [comment]
Should have some simple validation in Felix.

* IP forwarding as above
* File handle limits (set in the upstart job, but should validate as a belt and braces).

May want to add others later. Not critical for now, but worth sanity checking at startup point.

**Comment by neiljerram** [comment]
I've just been caught by this in my DevStack IPv6 testing.  IPv6 forwarding wasn't enabled on the host - grrr!  So I support working on this issue.

Just discussed options with @fasaxc, who is keen that we should if possible make Felix handle sysctl options (like IP forwarding) in a consistent way - and in particular consistent with what we've just implemented for rp_filter.

However there are 2 ways in which IP forwarding is not like rp_filter.

1. Possible values for IP forwarding are just 0 (don't forward) and 1 (forward).  There isn't a problem - as there is in the rp_filter case - that the 'all' value might be set to a higher value than 1 but that actually has a more restrictive (or unwanted) meaning.  So, if we're setting per-interface IP forwarding values, we don't need to care about the 'all' value.

2. Successful IP forwarding involves 2 interfaces, the inbound and the outbound.  It might be that IP forwarding needs to be set on both of them, or it might be just one - in which case, which?  I don't currently know - but anyway this is a possible structural difference from rp_filter.

We then discussed what we might do with IP forwarding.

1. Felix could just look at what is set, and complain loudly if it doesn't look right, but not actually change settings itself.

2. Felix could enable IP forwarding globally (i.e. with the 'all' value).

3. Felix could enable IP forwarding on each TAP interface individually, and require (=> document) that the operator enables IP forwarding on the particular fabric-facing interface(s) that should be used for routing instance data across the fabric; e.g. eth0.

I think the only sensible options here are (2) and (3).  Forwarding is fundamental to Calico operation, so I don't think it makes sense for Calico just to complain, so I'd rule out (1).

Therefore I propose a config option like this:

    # Control whether Calico enables IP forwarding globally (default value false), or only
    # on endpoint interfaces (value true).  In the latter case, the operator must also enable
    # IP forwarding on the fabric-facing interfaces that are used for routing endpoint data
    # between hosts and to/from the Internet.
    # per_interface_forwarding = false

**Comment by matthewdupre** [comment]
@beddari mentioned in IRC that https://github.com/projectcalico/calico/blob/master/debian/calico-compute.postinst should really be moved to better places (Neutron DHCP agent and Felix perhaps?).

**Comment by beddari** [comment]
So, I'm aware this is an endless ongoing debate but at least in the RHEL based world (a little less so perhaps in Debian) it is not expected for a package to self-configure other services at package installation time.

Documentation plus external helper scripts is much better. E.g that the package changes iptables rules and sysctl values breaks my automation setup.
