### ISSUE TITLE
Build improve for platform ppc64le

### ISSUE THREAD

**Issue by asicore** [projectcalico/felix#1890]
Hello!

When compiling `make bin/calico-felix ARCH=ppc64le` for version 3.1.1 on platform ppc64le, I got errors with gogo/protobuf and grpc packages.
I changed their versions in the glide.lock:
```
- name: github.com/gogo/protobuf
  version: 2c90c882111db4ea23b0f722d1554755d02dec5e
- name: google.golang.org/grpc
  version: a5986a5c88227370a9c0a82e5277167229c034cd
```

For migrating to a new felix's version I'll need to do the same steps, and it's very sad =(

Thanks

**Comment by fasaxc** [comment]
@asicore As of v3.2, we publish ppc images for Calico and the community maintain the PPC port.  Suggest you upgrade, then you won't have to build your own images.
