### ISSUE TITLE
PR: offer network subnet aggregation function  in an ebgp + ibgp environment

### ISSUE THREAD

**Issue by bretagne-peiqi** [projectcalico/felix#1896]
## Expected Behavior
In large scale cluster, where ibgp AS are connected by ebgp (e.x: using a ToR switch), we hope to aggregate different nodes routes in one route (one route by AS) in ebgp Switch to unburden the physical switch 

## Current Behavior
Currently node level network subnet is assigned by random, thus will populate the ebgp node
with many routes (one route by node) in a large scale situation 

## Possible Solution
add an config option to offer a linked network subnets in a AS so that they can be aggregated in edge router(ToR, example) 

## Context
large scale kubernetes cluster; we using calico: rr+ibgp + ebgp mode.  route reflector peer is deployed in bare-metal server using bird directly, ibgp is calico-node; we using our ToR as ebgp, however, ToR supports not only kubernetes-related node traffic, we hope to relieve its burden by aggregating routes in one or two. 

## Your Environment

* Felix version  (if using Felix binary directly `calico-felix --version`): 3.1.1
* And/Or, `calico/node` container version (if running Felix in a container): 17.03
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.9.3
* Etcd version (if using etcd datastore driver): 3.14
* Operating System and version: Linux, 4.11
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yeah, we need better documentation on how to do this today.

Right now, there is a way to configure Calico to use "per-rack" aggregation. Essentially, you can create an IPPool per rack, and then on each node configure the CNI plugin to use the correct ip pool based on the rack it is in.

It's not the easiest thing to configure, and our docs on it are basically non existent (tracked here https://github.com/projectcalico/calico/issues/547).

It would be even better if, for example, the IP Pools had some sort of node selector that could indicate which nodes are allowed to assign IP addresses from which pools.

**Comment by caseydavenport** [comment]
Here's a doc on how to do this in Calico v3.5: https://docs.projectcalico.org/v3.5/usage/assigning-ip-addresses-topology
