### ISSUE TITLE
For some nodes "calicoctl node status" showing as "Calico process is not running" 

### ISSUE THREAD

**Issue by jayakody** [projectcalico/felix#1942]
## Expected Behavior
"calicoctl node status" stating "calico process not running" for some nodes. However, all other functionalities seem to be ok. 

## Current Behavior

Here's the exact output from a working node:
```
[root@calico-node-18121 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+------------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+--------------+-------------------+-------+------------+-------------+
| 25.25.25.120 | node-to-node mesh | up    | 2019-01-12 | Established |
| 35.35.35.122 | node-to-node mesh | up    | 18:24:27   | Established |
| 35.35.35.123 | node-to-node mesh | up    | 18:24:27   | Established |
+--------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.

[root@calico-node-18121 ~]#
```

Here's the output from the problematic node:
```
[root@calico-node-18122]# calicoctl node status
Calico process is not running.
[root@calico-node-18122]# calicoctl get nodes
NAME
calico-node-18120
calico-node-18121
calico-node-18122
calico-node-18123

[root@calico-node-18122 ]#
```
However both felix & bird are up & running on this node:
```
[root@calico-node-18122 ~]# ps -aef | grep calico
root      11890  11872  0 Jan11 ?        00:13:39 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=calico-node-18122
root      12501  12497  2 Jan11 ?        01:38:29 calico-node -felix
root      12503  12498  0 Jan11 ?        00:00:29 calico-node -confd
root      12643  12496  0 Jan11 ?        00:03:43 bird6 -R -s /var/run/calico/bird6.ctl -d -c /etc/calico/confd/config/bird6.cfg
root      12644  12499  0 Jan11 ?        00:03:43 bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
root     181093 125870  0 13:12 pts/0    00:00:00 grep --color=auto calico
[root@calico-node-18122 ~]#
```

## Steps to Reproduce (for bugs)
I tried bringdown/bringup multiple times. Always end up with this situation where 2 out of the 4 nodes consistently shows "calico process not running" when executing "calicoctl node status" command. 

## Your Environment
4 node K8S system. Calico 3.4. 
```
[root@calico-node-18120 logs]# calicoctl --version
calicoctl version v3.4.0, build a7e09d5
```
Diag bundle is uploaded here:
https://transfer.sh/L6Wmn/diags-20190114_133015.tar.gz

Please let me know if you need further info/clarification.

**Comment by jayakody** [comment]
@caseydavenport It turns out I had an old calicoctl version lying around in the other 2 nodes that were having problems. Thanks for the pointer. 
It is not a bug. Let's close this PR.

**Comment by altblanc** [comment]
I bumped into it on my kubernetes cluster, and it hasn't fixed yet.
my kubernetes is v 1.13.4, and Calico is 3.7.
Any chance we can have this issue reopened?

**Comment by caseydavenport** [comment]
@altblanc could you please open a new issue and describe the steps you took and symptoms you saw? 

This particular one was resolved.
