### ISSUE TITLE
felix blocks all non-calico IPIP  traffic

### ISSUE THREAD

**Issue by squat** [projectcalico/felix#1943]
## Expected Behavior

It should be possible to use IPIP on nodes running calico with tunnel endpoints on non-calico nodes.
It would be great if calico appended, rather than inserted, the iptables rule to jump to cali-INPUT to the input chain in order to allow for other iptables rules to accept certain IPIP traffic.

## Current Behavior

Currently IPIP on nodes running calico are entirely owned by calico. Any iptables rules to accept the IPIP traffic from non-calico ipsets are quickly overridden as felix enforces that the “-j cali-INPUT” rule is always the first rule in the input chain, forcing all non-calico IPIP traffic to be dropped. Furthermore, the calico ipsets are themselves reconciled, so any efforts to change them are blown away.

## Possible Solution

If the cali-INPUT chain, or even the drop rule itself, were appended rather than inserted to the table, then an administrator could add other rules to filter an accept certain IPIP traffic.

## Context

Within a network I have some nodes that are not running calico and as well as a cluster of nodes running calico. I am creating IPIP tunnels and the required routes to enable full layer 3 networking between the nodes.

## Your Environment

* And/Or, `calico/node` container version (if running Felix in a container): v3.4.0
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): k8s
* Orchestrator version (if used): v1.13.1

**Comment by fasaxc** [comment]
You can configure append instead of insert as well as a whitelist of additional ipip endpoints in the Felix configuration.

**Comment by squat** [comment]
:thinking: huh cool. Thanks for the pointer. I appreciate that feature, though I still think Felix should not default to owning an entire protocol. I'll close this here for now.
