### ISSUE TITLE
Support exclude interface by pattern?

### ISSUE THREAD

**Issue by camper42** [projectcalico/felix#1945]
could you add support that exclude interface by pattern?
felix only support exclude interface by string match now

## Expected Behavior

support exclude interface by a pattern like `veth*` or `veth.*`
so interface change in docker bridge network not affect felix

## Current Behavior

`FELIX_INTERFACEEXCLUDE=kube-ipvs0,veth27afb87`
for each iface in `FELIX_INTERFACEEXCLUDE`, check by string compare (`InterfaceMonitor.isExcludedInterface`)

## Possible Solution

`InterfaceMonitor.isExcludedInterface` add regex/glob support
add pattern to `FELIX_INTERFACEEXCLUDE` or new configuration

## Steps to Reproduce (for bugs)

use k8s+calico and docker-bridge+in-house PaaS :)

## Context

we try to use k8s to replace our in-house PasS, and now its running on our servers at same time. 

## Your Environment

* `calico/node` container version (if running Felix in a container): v3.3.2
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): k8s
* Orchestrator version (if used): v1.13.1
* Etcd version (if using etcd datastore driver): 3.3.5
* Operating System and version: 4.4.6-gentoo

**Comment by caseydavenport** [comment]
Seems reasonable enough to me - @song-jiang any reason this couldn't be done?

**Comment by song-jiang** [comment]
@caseydavenport Seems reasonable to me too.
