### ISSUE TITLE
Cannot expose metrics on custom IP (but 0.0.0.0)

### ISSUE THREAD

**Issue by oblazek** [projectcalico/felix#1948]
When I run calico-node (felix) and enable metrics so that they are scraped by prometheus calico-node automatically binds to 0.0.0.0 and there is no option to change it to a custom IP.

## Expected Behavior
It should be possible to specify something like `PrometheusMetricsHost` in configuration file where we would specify which IP to use for binding. Default value would still be 0.0.0.0.

## Current Behavior
Currently it binds only to 0.0.0.0

## Possible Solution
It should be possible to specify something like `PrometheusMetricsHost` in configuration file where we would specify which IP to use for binding. Default value would still be 0.0.0.0.

## Steps to Reproduce (for bugs)

1. run calico-node on any linux machine
2. check `netstat -ntl` and look for port `9091`

## Your Environment
* `calico/node` image: quay.io/calico/node:v3.3.1
* Which orchestrator are you using: docker
* Orchestrator version (if used): docker-engine 17.05.0~ce-0~ubuntu-xenial

**Comment by caseydavenport** [comment]
Sounds like a good thing to do.

**Comment by caseydavenport** [comment]
This has been fixed and will be in v3.9.
