### ISSUE TITLE
modify code in felix package but no update by simply run 'make calico/node' in the parent directory

### ISSUE THREAD

**Issue by zppznn** [projectcalico/felix#1964]
Hi friends,

I was trying to add few feature to calico network and I started off with adding and changing log output. However I encountered an issue that the change I made in : $GOPATH/src/github.com/projectcalico/node/vendor/github.com/projectcalico/felix/dataplane/linux/ipip_mgr.go never get updated after I ran 'make calico/node' in the parent directory  :$GOPATH/src/github.com/projectcalico/node/ .

So I wonder how do I actually get my own code working and is calico pulling code everytime during the make process?

## Expected Behavior
The messages added in log should pop up in /var/log/calico/felix/current after successful builds and launches.

## Current Behavior
any changes are not taking effect right now.

## Possible Solution
longing for one.

## Your Environment
1. Ubuntu16.04
2. local workstation.
3. correct GOPATH and docker installed and configured.
4. Able to run 'make calico/node' and  launch dockers but not able to modify codes.

**Comment by caseydavenport** [comment]
`calico/node` pulls in a version of Felix using `glide`.

You can see the pin here: https://github.com/projectcalico/node/blob/master/glide.yaml#L16-L17

Typically, you'd update the glide.yaml file to point at the desired repo/commit, and then run `glide up -v` to update the vendor directory. 

From there, the build should use the specified version.

**Comment by zppznn** [comment]
With that being said, I need to update glide.yaml to point to my own repo to get changes updated. 
 
Btw. Can I run multiple dockers on one PC and connect them to my k8s cluster using only the tunl0 device? And what is the blackhole created in ip route table. Thanks!

**Comment by caseydavenport** [comment]
> Btw. Can I run multiple dockers on one PC and connect them to my k8s cluster using only the tunl0 device? And what is the blackhole created in ip route table. Thanks!

Yep, the tunl0 device is one per-node, multiple containers can send traffic over it.

The blackhole routes are installed as part of Calico's route aggregation logic.

**Comment by zppznn** [comment]
Thank you so much!
