### ISSUE TITLE
unwanted log level

### ISSUE THREAD

**Issue by daixiang0** [projectcalico/felix#1987]
For https://github.com/projectcalico/felix/blob/master/usagerep/usagerep.go#L151
## Expected Behavior

warn level or even higher.

## Current Behavior
info level

I am not familiar with the rule log level, but for me, i refer it in higher level.

**Comment by daixiang0** [comment]
any input?

**Comment by caseydavenport** [comment]
I think this is fine where it is - it's not actually going to impact behavior or performance, so I don't think it warrants being higher than INFO.
