### ISSUE TITLE
Redundant warning in log when not using VXLAN

### ISSUE THREAD

**Issue by eranreshef** [projectcalico/felix#2027]
I've seen unexplained warnings in my logs:
> int_dataplane.go 354: Failed to query VXLAN device error=Link not found

## Expected Behavior
When not using VXLAN, no VXLAN related warning should appear in the logs.

## Current Behavior
The above log warning is printed on every pod startup.

## Possible Solution
Change the logic around https://github.com/projectcalico/felix/blob/00c71c865d99c1884143ea7b0bd2954e26092bbe/dataplane/linux/int_dataplane.go#L354 so that a case when there is no VXLAN device to remove won't cause a warning in the logs.

## Steps to Reproduce (for bugs)
1. Start a calico node container without overriding the default `false` value for `VXLANEnabled` in FELIX's config.
2. Watch the pod's log

## Context
Nothing important, just hurts my eyes.

## Your Environment

* `calico/node` container version (if running Felix in a container): 3.7.2
* Which orchestrator are you using : Kubernetes
* Orchestrator version (if used): 1.11.9
* Etcd version (if using etcd datastore driver): 3.3.12
* Operating System and version: CoreOS-stable-2023.5.0

**Comment by caseydavenport** [comment]
Would be great to fix - I think it's just a matter of cleaning up the log text.

Any takers?
