### ISSUE TITLE
No possible to disable --random-fully 

### ISSUE THREAD

**Issue by stamak** [projectcalico/felix#2089]
We have a network problem related to conntrack on **3.5.7**
I have tried a lot but Only downgrade to version 3.1 helps
Seems it's related to https://github.com/projectcalico/felix/pull/1901
Having possibility to disable --random-fully on 3.5.7 can help to eliminate a calico upgrade

I am not
100% sure its ONLY **--random-fully** related as well new calico version

## Expected Behavior
It would be nice to have possibility to disable --random-fully 

## Current Behavior
--random-fully is added automatically once it detects iptables version supports it

## Possible Solution
Add config variable e.g. *IptablesRandomFully: true(default)/false* 

## Steps to Reproduce (for bugs)
Have a problem with new calico version 3.4+

## Your Environment

*  Version
```
calico-node -v
Threshold time for bird readiness check:  30s
v3.5.7

docker images
calico/node                                                  v3.5.7                    0654090e64a6        4 weeks ago         72.7MB
```

*  Kubernetes:  v1.14.4
* Operating System and version:
```
Container Linux by CoreOS 2079.6.0 (Rhyolite)
uname --r
4.19.43-coreos-r1
```

**Comment by fasaxc** [comment]
@stamak Please can you explain what the actual problem is?  What symptoms are you hitting?

**Comment by fasaxc** [comment]
How did you upgrade?  Make sure you apply the _new_ Calico manifest; we often make manifest changes so simply revving the image doesn't necessarily just work.

**Comment by stamak** [comment]
I have a problem with the same connection on worker node and pod 
As pod tries to keep connection  (42304-8774) but on worker node after some period of time it changes port 65265-->56308 (pod port 42304). Also it changes **Seq** and **Ack** to **1** on worker node. You can see it on below pictures

pod tcpdump
![pod_tcpdump](https://user-images.githubusercontent.com/5549415/62117831-5c65fd00-b2c5-11e9-9be2-08cf4b989129.png)

worker node tcpdump
![worker_tcpdump](https://user-images.githubusercontent.com/5549415/62117810-4fe1a480-b2c5-11e9-9cb5-ca1eaa199e1e.png)

**Comment by fasaxc** [comment]
Looks like the client is just reconnecting?  There's a FIN packet ending the connection.

**Comment by fasaxc** [comment]
@stamak Looks like someone put up a PR with a prototype that allows random-fully to be disabled: https://github.com/projectcalico/felix/pull/2310

**Comment by uablrek** [comment]
It has been noticed in K8s that then combination of vxlan offload and --random-fully causes delays. Please see discussion in the sig/network meeting  May 28 2020;
https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit

**Comment by fasaxc** [comment]
Fixed by with FeatureDetectOverride flag.
