### ISSUE TITLE
Incorrect processing of Kubernetes Node's spec.PodCIDRs list

### ISSUE THREAD

**Issue by akolosov-a** [projectcalico/felix#2403]
## Expected Behavior
No warnings about Node PodCIDR parsing in logs when nodes have `spec.podCIDR` and `spec.podCIDRs` properly set.

## Current Behavior
Constantly repeating warning messages (about 12 per minute) about Node PodCIDR parsing:
```
2020-06-26 11:27:38.645 [WARNING][35] felix/felixnodeprocessor.go 232: Failed to parse Node PodCIDR CIDR="" error=invalid CIDR address:
```

## Possible Solution
My brief investigations led me to this code in libcalico-go: https://github.com/projectcalico/libcalico-go/blob/871c78fe00ea74d40da7012bc4b2377493be11b7/lib/backend/k8s/resources/node.go#L285-L290. `calicoNode.Status.PodCIDRs` is initialized with the list of the proper length filled with empty strings, but then actual CIDRs are appended to that list. As a result `calicoNode.Status.PodCIDRs` contains both empty strings and CIDRs which later causes node processor to parse empty strings as CIDRs (https://github.com/projectcalico/libcalico-go/blob/5728ce4bda3ab84d314323de12800671e6f9276f/lib/backend/syncersv1/updateprocessors/felixnodeprocessor.go#L229).

## Steps to Reproduce (for bugs)
1. Configure calico-node with `USE_POD_CIDR="true"`.
2. Configure calico CNI plugin to use `host-local` IPAM plugin.
3. Check calico-node's logs 

## Context
I'm using canal.

## Your Environment

* `calico/node` container version (if running Felix in a container): 3.15.0
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.16.10
* Operating System and version: Flatcar Container Linux by Kinvolk stable (2512.2.0)

**Comment by caseydavenport** [comment]
I've submitted a fix here: https://github.com/projectcalico/libcalico-go/pull/1278
