### ISSUE TITLE
Open iptables rules not delete when used hostPort

### ISSUE THREAD

**Issue by iptizer** [projectcalico/felix#2406]
The [initial issue has been opened in Calico](https://github.com/projectcalico/calico/issues/3412), but some debugging led to the assumption that the problem actually lies in Felix. Feel free to correct me if I'm wrong.

As far as I currently know only **CentOS8** / Felix backend **NFT** is affected. That is the reason why I believe the problem lies in Felix and not in Calico itself. As (even though I have not tested), probably the problem does not exist in general.

## Expected Behavior

The following command, with the following manifest,shall not lead to orphaned iptables chains. For a more detailed description see my post in the [Calico Issue](https://github.com/projectcalico/calico/issues/3412#issuecomment-650779435).

```sh
kubectl apply -f nginx.yml; sleep 15 ; kubectl delete -f nginx.yml ; sleep 15 ; kubectl apply -f nginx.yml
```

Manifest:

```sh
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: troubleshoot
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    ports:
    - containerPort: 80
      hostPort: 10081
      name: http
    - containerPort: 443
      hostPort: 8443
      name: https
    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
```

## Current Behavior

iptables chains sum up and are not deleted.

## Possible Solution

Write a script that checks whether the destination referenced in the orphaned iptables chain still exists. This could be done, but Calico should recognize this, should it?

## Steps to Reproduce (for bugs)

Setup Calico on CentOS8 with kubespray. Execute the commands with the manifest from above.

## Context

The hostPorts are then simply not reachable until the rules/chains are deleted manually or the machine is rebooted.

## Your Environment

* CentOS8
* Setup performed with kubespray (Kubernetes) [2.13.2](https://github.com/kubernetes-sigs/kubespray/releases/tag/v2.13.2).
* Running on node: `docker.io/calico/node:v3.13.2`
    * with `docker.io/calico/cni:v3.13.2`

```sh
$ calicoctl version
Client Version:    v3.14.1
Git commit:        c97876ba
Cluster Version:   v3.14.0
Cluster Type:      k8s,kdd,bgp,kubeadm
```

* `quay.io/coreos/etcd:v3.3.12`

**Comment by caseydavenport** [comment]
Let's keep discussion on the original issue, since there seems to be a fair bit of diagnosis there ( we don't look too closely at which repo issues are opened in!)

https://github.com/projectcalico/calico/issues/3412 for reference
