### ISSUE TITLE
Routing is not correctly after change node ip in VXLAN CrossSubnet mode

### ISSUE THREAD

**Issue by lyyao09** [projectcalico/felix#2494]
## Expected Behavior

In **CrossSubnet** mode of vxlan, the routing is correctly after changing the node ip.
## Current Behavior

In **CrossSubnet** mode of vxlan, the routing is not correctly after changing the node ip.
## Steps to Reproduce (for bugs)

Environment：
Node A：100.100.5.10/16（eth0）
Node B：100.100.5.42/16
Node C：172.16.5.10/16
1. Changing IP of Node A to 100.101.5.10/16 on eth1, by calicoctl apply -f node.yaml
2. Check Route table before IP changing(e.g. 177.177.12.0/26 via eth0)
3. Check Route table after IP changing(e.g. still 177.177.12.0/26 via eth0 instead of 177.177.12.0/26 via vxlan.calico)
4. Check felix log, seems like:(After modifying the node ip, it should belong to a different subnet, while logs print **same_subnet:true**)

`2020-09-09 12:23:26.127 [INFO][61] felix/int_dataplane.go 1117: Received *proto.RouteUpdate update from calculation graph msg=type:REMOTE_WORKLOAD ip_pool_type:VXLAN dst:"177.177.12.0/26" dst_node_name:"single1" dst_node_ip:"100.100.5.42" same_subnet:true nat_outgoing:true`

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): v3.15.1
* And/Or, `calico/node` container version (if running Felix in a container): v3.15.1
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos):Kubernetes
* Orchestrator version (if used):
* Etcd version (if using etcd datastore driver): 3.3.11
* Operating System and version:CentOS 7.6
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> dst_node_ip:"100.100.5.42"

This is within the `100.100.5.10/16` subnet, so I think the log is correct. I'm not sure I fully understand which routes you're expecting to be on the same subnet, and which should be over VXLAN.
