### ISSUE TITLE
Multi arch support?

### ISSUE THREAD

**Issue by max8899** [projectcalico/felix#2504]
https://github.com/projectcalico/felix/blob/7299ad1dc67c69f0452520b86f3c43bc35862287/bpf-gpl/Makefile#L26

Calico manage container networks in Kubernetes and it ships with multi-arch support, and this project will be build each calico-node builds, why is this Makefile take amd64 arbitray?

**Comment by caseydavenport** [comment]
I'm guessing that our eBPF dataplane is amd64 only. @fasaxc is that right?

**Comment by fasaxc** [comment]
Yes, we haven't tried it on other platforms.  The other platforms are community maintained; we'd welcome PRs to make it work on more architectures.
