### ISSUE TITLE
Calico fails kubernetes e2e tests for "session affinity timeout" in BPF mode

### ISSUE THREAD

**Issue by hakman** [projectcalico/felix#2537]
While enabling the eBPF dataplane in kops, we noticed that the "session affinity timeout" tests are [failing](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/10069/pull-kops-e2e-cni-calico/1318137792328372224):
```
[sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] 
```

## Expected Behavior
Don't fail the tests.

## Current Behavior
Tests are failing because the implementation is using a hash table to pick the backend so that it sticks to the same backend even after the affinity expires.
https://github.com/projectcalico/felix/blob/50246bf3838ba747d42f07ba7eb6e961fdc8f742/bpf-gpl/nat.h#L274-L286

## Possible Solution
Quoting @fasaxc:
> I'm inclined to just drop the stable hash idea and follow the upstream model.

## Steps to Reproduce (for bugs)
Run the e2e tests on a Kops based cluster with Calico and BPF enabled.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/10069/pull-kops-e2e-cni-calico/1318161208548790272

## Context
n/a

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): 3.16.3
* And/Or, `calico/node` container version (if running Felix in a container): 3.16.3
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.19.3
* Etcd version (if using etcd datastore driver): 3.4.3
* Operating System and version: Ubuntu 20.04.1
* Link to your project (optional): https://github.com/kubernetes/kops/pull/10069

**Comment by fasaxc** [comment]
@tomastigera remembered a reason why we use a hash; it prevents concurrent connections from getting different affinities at start of day.  We can probably still live without.

**Comment by fasaxc** [comment]
We decided to change the scheme to random and accept that there is a potential race if two connections are made from the same IP at the same time.
