### ISSUE TITLE
FELIX_ETCDENDPOINTS not respected.

### ISSUE THREAD

**Issue by dElogics** [projectcalico/felix#2581]
It seems the only way to set the ETCD endpoints is to use the config file, otherwise calico-node outputs -- 
[ERROR][652] felix/daemon.go 227: Failed to create datastore client error=no etcd endpoints specified
repeatedly.

Set the following environment variables -- 
export FELIX_DATASTORETYPE=etcdv3
export FELIX_ETCDENDPOINTS=http://192.168.3.2:2379

Run felix in the same shell -- 
/usr/bin/calico-node -felix

**Comment by caseydavenport** [comment]
@dElogics could you share the full log from the failed Felix instance? It should show the config loading and might give a clue what's going on.

**Comment by dElogics** [comment]
[felix_logs.log](https://github.com/projectcalico/felix/files/5551101/felix_logs.log)

Log level is debug

**Comment by caseydavenport** [comment]
I will take a look at those, thanks!

For what it is worth, I believe you can use `ETCD_ENDPOINTS` instead of `FELIX_ETCDENDPOINTS` and it should work for you. That is what most of our manifests use when in etcd mode.

**Comment by dElogics** [comment]
No, I even tried that, it doesn't work. I had to use the config.

**Comment by lmm** [comment]
@dElogics I'm going to close this for now since it's been a while and but if you're still having issues with this, please reopen the issue, thanks!
