### ISSUE TITLE
I object to being a daemon

### ISSUE THREAD

**Issue by felixpalmer** [projectcalico/felix#2602]
## Expected Behavior
Daemons should be drawn from the ranks of the serving staff, not the aristocracy

## Current Behavior
A scandal

## Possible Solution
Rename component to Josh

**Comment by fasaxc** [comment]
Yessir

/me doffs cap

:rofl: I thought you'd be flattered!

**Comment by felixpalmer** [comment]
I must confess it did make me smile. Now when people ask me if I've heard about the catfood that's named after me (again) I can say "no, but check out this wicked daemon!"

**Comment by caseydavenport** [comment]
I can confirm that felix is a Daemon, and that this is working as intended.
