### ISSUE TITLE
Unable to set Failsafe ports to 'none' to disable them

### ISSUE THREAD

**Issue by treydock** [projectcalico/felix#2618]
## Expected Behavior

Per docs I'd expect `FelixConfiguration` to allow `none` for `FailsafeInboundHostPorts` and `FailsafeOutboundHostPorts`.

## Current Behavior

When I attempt to disable Inbound or Outbound failsafe ports I get this error:

```
cannot parse string 'none' into field FelixConfigurationSpec.failsafeInboundHostPorts of type []v3.ProtoPort
```

## Steps to Reproduce (for bugs)

```
[root@kubecontroller-dev kubernetes-configs]# cat calico/felix-default.yaml 
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfLogLevel: ""
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
  FailsafeInboundHostPorts: none
  FailsafeOutboundHostPorts: none

[root@kubecontroller-dev kubernetes-configs]# calicoctl apply -f calico/felix-default.yaml 
Failed to execute command: error parsing document: cannot parse string 'none' into field FelixConfigurationSpec.failsafeInboundHostPorts of type []v3.ProtoPort
```

## Context

I have applied several global network policies to restrict host traffic and I would like to now disable the failsafe rules.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): 
* And/Or, `calico/node` container version (if running Felix in a container): v3.15.3
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.19.4
* Etcd version (if using etcd datastore driver):
* Operating System and version: RHEL 7.7
* Link to your project (optional):

**Comment by treydock** [comment]
Found this works:

```
  FailsafeInboundHostPorts: []
  FailsafeOutboundHostPorts: []
```

Not sure if that's expected, I see tests in this repo that `none` should work, but maybe this is an issue with calicoctl and not this repo?

**Comment by mgleung** [comment]
Hi @treydock , can you point me towards the tests that you mention? I am surprised that we were expecting `none` to be a valid value for the list of ports, but I could just be missing something.

**Comment by treydock** [comment]
I saw what looks like relevant tests here: https://github.com/projectcalico/felix/blob/master/config/config_params_test.go#L397-L398. I didn't look too closely at where those values are used so could be I just associated the presence of `FailsafeInboundHostPorts` incorrectly.

Also the docs here mention setting value to `none`: https://docs.projectcalico.org/archive/v3.17/reference/host-endpoints/failsafe.  Same for here: https://docs.projectcalico.org/archive/v3.17/reference/felix/configuration.  There are other references which mention its a list of ports like here: https://docs.projectcalico.org/reference/resources/felixconfig so maybe I just was referencing the wrong docs when I thought `none` was valid?

**Comment by caseydavenport** [comment]
I believe this is because there are multiple ways to set this:
- In the API via the FelixConfiguration resource, where an empty list signifies no ports.
- As an environment variable, where empty string means "use defaults" and the value "None" means "none"
