### ISSUE TITLE
Native nftables support

### ISSUE THREAD

**Issue by pavels** [projectcalico/felix#2652]
I would like to ask if you are considering adding native nftables support instead of the iptables compatibility layer.

It would be nice to see calico live in it's own table, also nftables allows atomic rules update (even whole tables)

With something like this https://github.com/google/nftables no command line tools execution needed as well.

Would you consider adding this, or would you accept PRs that would try to implement something like this?

**Comment by caseydavenport** [comment]
@fasaxc what do you think? 

My feeling is that it would be nice to have nftables support, but that it might not have as much of a place any more between the iptables backend and the eBPF backend?

It's a fair bit of work to get a data plane implementation done. One thing you might consider doing is taking the approach of the calico-vpp project, and build an external data plane that is decoupled from the core felix code: https://github.com/projectcalico/vpp-dataplane

**Comment by fasaxc** [comment]
Yes, it'd be nice to have so that we can be ready when distros start to move to clean nft-only.

Sadly, there's no great driver apart from "things move on".  It seems that nftables is about 2x _slower_ than iptables rule-for-rule in my tests.  It might be a win for the kube-proxy use case where an nft map could be used to do DNAT lookups but (1) kube-proxy isn't part of Calico and (2) even there, you need hundreds of services before the map outperforms 100 sequential iptables rules.  (I was very disappointed by these numbers when I collected them and I hope nft is able to improve!)

**Comment by fasaxc** [comment]
FWIW, iptables always had atomic updates to the whole table and Calico relied on that.  That was its weakness and the reason that nftables was introduced: to give an API that allows for smaller updates to parts of a table in a clean way.

**Comment by pavels** [comment]
The performance issues are new to me. Interesting.

eBPF looked very promising, but it has it's own problems. I tried implementation from Cilium project and Calico eBPF datapath and both suffers similar problems. I particular if you have multiple VLANs on single physical interface. Also it needs to deal correctly with the situation that interfaces come and go (like VPN interfaces). 

The most interesting thing about `nftables` for me so far is it's readability. Each service could have it's own table and overall the output of the `nft` can be less messy (unless you use the compatibility layer, than it is kind of mess). One could argue that that is no issue as you don't need to bother - until you do when something stops working, than ability to understand what is actually happening on the firewall / NAT layer is priceless. `eBPF` in this regard is the worst - it is basically black box, if something breaks, admin has nearly zero options to see what's happening inside. But is is fast, yes.

**Comment by fasaxc** [comment]
Please can you elaborate on the problems you were seeing in BPF mode?  Maybe you just needed to change the interface detection regex.

**Comment by pavels** [comment]
> Please can you elaborate on the problems you were seeing in BPF mode? Maybe you just needed to change the interface detection regex.

Here https://github.com/projectcalico/felix/issues/2654
