### ISSUE TITLE
About the tunnel about IPV6 address

### ISSUE THREAD

**Issue by mzzgaopeng** [projectcalico/felix#2883]
At present, calico does not support vxlan tunnel of ipv6, but ipv6 already supports vxlan tunnel. Is there any concern that calico does not support vxlan mode of ipv6 separately?

If the IPV6 tunnel is supported, then the entire IPV4 network interconnection can be solved without relying on BGP
Is there a schedule for such an idea?

**Comment by caseydavenport** [comment]
Please don't open several issues regarding the same topic: https://github.com/projectcalico/calico/issues/4709
