### ISSUE TITLE
Calico doesn't allow VMs to send/receive from/to IP addresses specified by Neutron's allowed-address-pairs

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/felix#337]
Neutron, since Havana, allows configuring additional allowed source IP addresses for a port, i.e. that that port is allowed to appear to be sending from.
https://blueprints.launchpad.net/neutron/+spec/allowed-address-pairs
https://docs.google.com/document/d/1hyB3dIkRF623JlUsvtQFo9fCKLsy0gN8Jf6SWnqbWWA/edit

In an OpenStack environment, Calico should allow VMs to send/receive from/to those additional IP addresses, but currently it doesn't.

**Comment by fasaxc** [comment]
Felix supports multiple IPs per endpoint, I guess that makes this a plugin issue?

**Comment by neiljerram** [comment]
Yes, agreed.

**Comment by fasaxc** [comment]
Feels like something we need to fix unless we can argue it's not needed with Calico.

**Comment by ed-harrison** [comment]
@neiljerram @Lukasa Just checking - is this still an issue since the recent plugin rewrite?

**Comment by Lukasa** [comment]
Yes.

**Comment by ed-harrison** [comment]
In that case, @neiljerram can you comment on how important you think this is?  i.e. is it really a 1.0 item?

**Comment by neiljerram** [comment]
Technically it's a failure to implement part of the Neutron API.  In practice, perhaps not a very important one.

Coincidentally, proper support for allowed-address-pairs has come up today on the ML.  So it looks like there's at least one other existing Neutron implementation that hasn't done this either.

On balance, I feel we could release 1.0 without this.

**Comment by fasaxc** [comment]
@neiljerram what's the status of this one?  I thought we added this support.

**Comment by neiljerram** [comment]
No, don't believe so. I recall someone on IRC/Slack saying they might do this, but it hasn't materialized yet.

**Comment by neiljerram** [comment]
This is a networking-calico issue, and now being tracked and worked on under https://bugs.launchpad.net/networking-calico/+bug/1604226.  So closing this issue.
