### ISSUE TITLE
Possible speed up for DHCP serving - dhcp-authoritative & no-ping

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/felix#43]
Felix Schüren writes at http://lists.projectcalico.org/pipermail/calico/2014-November/000051.html:

In order to speed up DHCP replies for new VMs (and thus VM boot time), I
think adding
 --dhcp-authoritative
 --no-ping
to dnsmasq should be safe & sane.

 --dhcp-authoritative
 Should  be  set  when dnsmasq is definitely the only DHCP server on a
network.  For DHCPv4, it changes the behaviour from strict RFC
compliance so that DHCP requests on unknown leases from unknown hosts
are not ignored. This allows new hosts to get a lease without a tedious
timeout  under  all  circumstances.  It also allows dnsmasq to rebuild
its lease database without each client needing to reacquire a lease, if
the database is lost. For DHCPv6 it sets the priority in replies to 255
(the maximum) instead of 0 (the minimum).

 --no-ping
(IPv4 only) By default, the DHCP server will attempt to ensure that an
address in not in use before allocating it to a host. It does this by
sending an ICMP echo request (aka "ping") to the address in question. If
it gets a reply, then the address must already be in use, and another is
tried. This flag disables this check. Use with caution.

**Comment by nbartos** [comment]
I agree, this sounds like a good idea.

**Comment by fasaxc** [comment]
Since DHCP has been a bottleneck, should we look into this again?

**Comment by fasaxc** [comment]
I believe `--dhcp-authoritative` is incorrect for Calico.  When we have multiple networks configured, we currently bridge together the DHCP agents (or, more precisely, tell them to behave as if they are bridged).  This means that they are not authoritative.

**Comment by neiljerram** [comment]
Note: For deployments using the Calico DHCP agent (as opposed to the reference Neutron one), @fasaxc's last comment doesn't apply, and so --dhcp-authoritative would be correct.

**Comment by neiljerram** [comment]
Moved to https://bugs.launchpad.net/networking-calico/+bug/1629316
