### ISSUE TITLE
Linux kernel treats ICMP type/code 255 as a wildcard

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/felix#451]
Felix programs a rule like this, expecting it to match packets of type 255 and code 255 only:

```
-A felix-p-_5f77875ac4e22aa-i -p icmp -m icmp --icmp-type 255/255 -j RETURN
```

But iptables-save returns it as this:

```
-A felix-p-_5f77875ac4e22aa-i -p icmp -m icmp --icmp-type any -j RETURN
```

Assuming it is correctly reporting what the kernel is doing, this is broken.

I think that means we either need to whitelist only the valid ICMP types or switch to using a different approach as outlined in #424.

**Comment by fasaxc** [comment]
@neiljerram  Bit annoying that Openstack allows arbitrary matching here but that's awkward to support in the kernel.  Is there any way to tell Openstack we can't support that combination?  If not, I guess we just have to figure out another way to implement this in felix (ideas in #424).

**Comment by Lukasa** [comment]
@fasaxc As far as I know there's no way to report the limitation to OpenStack.

Given that it can be programmed elsewhere, I'd be interested to see what that security group rule turns into using a different plugin. I may be able to bully someone else in the org into testing for me.

**Comment by fasaxc** [comment]
I'm erring towards the u32 approach described in #424.  It feels wrong but I think we should be able to isolate it and build a good FV for it.  It is one of the explicit examples for the u32 match extension.

**Comment by neiljerram** [comment]
Is there any urgency here?  Note that ICMP type 255 isn't even a defined value yet (except as 'reserved').  I'll move this out to 1.0 for now; happy to move back if that's the wrong thing.

**Comment by fasaxc** [comment]
I can't see this ever bubbling up to the top of the list give that ICMP 255 isn't a valid value.
