### ISSUE TITLE
DHCP checksum fixing rule is too broad: in POSTROUTING chain, not OUTPUT

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#709]
This is a split from issue #40.

We currently use a rule that looks like `iptables -A POSTROUTING -t mangle -p udp --dport 68 -j CHECKSUM --checksum-fill`, but this is too broad.

We should make the rule more specific - @nbartos suggests `iptables -t mangle -A OUTPUT -o tap+ -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill`.

The most important thing is moving from the POSTROUTING to OUTPUT chain, so we don't run the rule over forwarded packets.  This will need to be upstreamed.

**Comment by neiljerram** [comment]
Moved to https://bugs.launchpad.net/networking-calico/+bug/1629309
