### ISSUE TITLE
Unnecessary IPv6 RS delay listed in our documentation

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/felix#766]
http://docs.projectcalico.org/en/latest/ipv6.html currently adds some configuration to add a 10s router solicitation delay.  This was added due to #12.  We should remove this additional configuration note, but first we should explicitly test without it.

**Comment by eepyaich** [comment]
@lwr20 Could you test IPv6 without this piece of RS delay configuration, at some point, please?

**Comment by fasaxc** [comment]
Closing because that doc has been retired.
