### ISSUE TITLE
Filtering on IP protocol 0 causes all rules to be silently rejected

### ISSUE THREAD

**Issue by Brook-Roberts** [projectcalico/felix#777]
Adding a security group rule in Openstack, through Horizon, that filters on IP protocol 0, causes all other rules in that security group to stop taking affect.

I believe it's expected that we can't implement this rule, however:
a) The user isn't informed that their rule wasn't allowed, so if they intended to put in a different rule (e.g. allowing a different protocol) it won't be obvious that they put in the wrong thing
b) Since the user isn't informed, they won't realise straight away that the rest of their rules also aren't working.

Likely to be a particular pain for people using scripts, which could well mistakenly enter such rules.

**Comment by fasaxc** [comment]
Two approaches we can take here:

* Find a way to police this in the neutron plugin.  Does it just work if we raise an exception when we stop a bad rule?
* Wait for status reporting in felix which will let us report the failure to program back up to neutron.  This may not be very visible in the UI, though.

**Comment by fasaxc** [comment]
We could also improve limit the "blast" radius to only the single rule by making a safe approximation.

**Comment by neiljerram** [comment]
What _should_ filtering on IP protocol 0 do?

**Comment by fasaxc** [comment]
@neiljerram Not sure, is there a Neutron blueprint or something that defines the valid values?

**Comment by fasaxc** [comment]
@eepyaich just testing your filtering rules

**Comment by eepyaich** [comment]
Thanks @fasaxc; I think they need more work...

**Comment by neiljerram** [comment]
Moved to https://bugs.launchpad.net/networking-calico/+bug/1629308
