### ISSUE TITLE
etcd should not be a hard requirement, interface should be pluggable

### ISSUE THREAD

**Issue by jfarrell** [projectcalico/felix#782]
If Zookeeper or Consul are all ready in use with in a given stack then Calico should be able to take advantage of the existing running infrastructure rather than requiring etcd to be added to the stack

**Comment by fasaxc** [comment]
It's a good idea but I'm not sure when we'll get to it.  Would you be interested in contributing an alternative back-end?

**Comment by siddharthist** [comment]
This would be awesome. We have Consul as one of our core components in [mantl.io](http://mantl.io), and would love to be able to use its K/V store as a backend, rather than adding etcd.

**Comment by kingpong** [comment]
In the unlikely event you aren't aware of it, [libkv](https://github.com/docker/libkv) provides an abstraction that would make plugging in consul, etc. relatively easy.

**Comment by siddharthist** [comment]
@kingpong That library is in Golang, whereas Calico is written in Python. Could it feasibly be used?

**Comment by Lukasa** [comment]
@siddharthist I believe that Go can expose a cdecl ABI, which means you can call into it from CFFI if you're prepared to work hard enough.

**Comment by philips** [comment]
@kingpong As an aside, libkv is a pretty suboptimal abstraction that will continue to get worse as etcd adds new features and better clients via [etcd v3](https://coreos.com/blog/etcd-v230.html).

**Comment by kingpong** [comment]
@siddharthist haha, no, sorry. Been looking at a lot of docker-related stuff recently and I have Go on the brain. Sorry for the noise.

**Comment by frankscholten** [comment]
We like to add Calico to [minimesos](https://github.com/ContainerSolutions/minimesos/issues/420) and if it uses Zookeeper it would make things easier.

**Comment by xiaods** [comment]
it should be implement asap

**Comment by fasaxc** [comment]
We're actually working on making the backend more pluggable as part of adding support for etcd v3.  However, there's no concrete plan to support Zookeeper or Consul; I think we'd need a community contribution to add that.

**Comment by racktear** [comment]
@fasaxc I have expertise in consul and I'm familiar with python consul library. How may I help?

**Comment by fasaxc** [comment]
@racktear the API is now in place in master (of libcalico-go); we've started by adding a direct Kubernetes (etcdless) backend.

The backends are stored in this directory (etcd and k8s so far): 
https://github.com/projectcalico/libcalico-go/tree/master/lib/backend

I'd expect the create, update, delete function to be a  pretty straightforward copy of the etcd ones but the Syncer API is a bit tricky to get right.   If you want to look at the etcd one for inspiration, don't look at master, I've done a lot of cleanup and added fixes under this PR: https://github.com/projectcalico/libcalico-go/pull/246.

I suggest having a read of that code, then joining the calico-dev channel on our slack to discuss the design further.

**Comment by fasaxc** [comment]
Moving this to the "Future Ideas" pile because it depends on someone volunteering to contribute the code.

**Comment by racktear** [comment]
I will familiarize myself with the code base. Currently Calico looks like an ideal solution for our use case, so I'm willing to at least try to do the implementation.

**Comment by caseydavenport** [comment]
@racktear feel free to reach out to me with any questions.  I recently implemented the k8s datastore driver.

**Comment by aensidhe** [comment]
@caseydavenport @fasaxc I started to work on consul integration with @racktear and I lack of knowledge of domain model. K8s and etcd apis are very different in implementations - why is that?

**Comment by fasaxc** [comment]
@aensidhe The etcd API is a simple KV store whereas the k8s API is typed so we need to do a lot of mapping.  Since consul and etcd are very similar, a consul version should be much more similar to the etcd backend.  

The create/update/delete operations should be almost identical to the ones in here: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/etcd/etcd.go

The etcd syncer has some complexity to deal with resync at high scale (explained in https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/etcd/syncer.go#L72).  If you want to start simple for low scale, it wouldn't need to be so complex, you could use a single goroutine that simply:

- loaded a snapshot and sent it key-by-key
- started polling at the snapshot index, sending updates key-by-key

**Comment by caseydavenport** [comment]
> etcd should not be a hard requirement, interface should be pluggable

I think this is essentially done, correct?

There's a pluggable datastore driver interface in libcalico-go, and we've already got two datastore drivers which implement it (etcdv2, kubernetes).

I suspect this issue should be closed in favor of specific issues / PRs for other backends.

**Comment by zrml** [comment]
How is this PR going?
I agree it should be pluggable. Tying yourself to a single K/V store seems unwise IMO.
Consul needed here.
Thanks
