### ISSUE TITLE
Should use EPEL copy of etcd, not manual download

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/felix#839]
Packaged installs are better than manually downloading the binary.  There's a 2.0.13-2.el7 available in rhel-7-server-extras-rpms which we should just use.

**Comment by fasaxc** [comment]
We've had a lot of questions about installing etcd, feels like this could be raised to medium priority.

**Comment by eepyaich** [comment]
Indeed - several people at DockerCon said they wanted to try Calico but were put off by having to understand how to install/configure etcd.  

Clearly production deployment will need some real etcd knowledge, but for early trials and tests, some simple instructions using a packaged install, would be much appreciated by the community!  Not sure who is best placed to write such instructions, though - any suggestions?

**Comment by matthewdupre** [comment]
I think there's a second issue here, which is configuration.

For OpenStack we provide very specific instructions that work well enough for a demo (non-clustered) deployment.  They'd be a bit nicer on EL7 with a package, but that's a fairly small win (the service file the package comes with (if any) is probably not suitable).

For Docker we're generally vaguer about how to set etcd up; and this sounds a bit like a repeat of the BIRD configuration story.  Maybe what we really need is a script / container that just sets up etcd?

**Comment by eepyaich** [comment]
I think we have some of that for people who don't really care what's happening (i.e. we have vagrant scripts which will set everything up for you).  It's the people who want to know what is going on who I think will be interested in some instructions.  Maybe we should just break out what we've got in the OpenStack docs into a separate page which we can point people at...

**Comment by fasaxc** [comment]
Moved to https://github.com/projectcalico/calico/issues/249
