### ISSUE TITLE
List of config parameters in docs is incomplete

### ISSUE THREAD

**Issue by alexwlchan** [projectcalico/felix#874]
Looking at our configuration doc (http://docs.projectcalico.org/en/stable/configuration.html) and [calico/felix/config.py](https://github.com/projectcalico/calico/blob/master/calico/felix/config.py), we seem to be missing a few parameters:
- IpInIpEnabled
- IpInIpMtu
- ReportingIntervalSecs
- ReportingTTLSecs
- EndpointReportingEnabled
- EndpointReportingDelaySecs

This doc should be updated with new config parameters.

**Comment by fasaxc** [comment]
Those are left out because they're somewhat "internal".  I.e. they're config from Felix's point of view but they're set automatically by the orchestrator.
