### ISSUE TITLE
The "Getting involved" documentation needs updating to point to calico-containers and other calico-container related repos

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/felix#976]
The involved.rst document currently points at calico-docker.

-  The calico-docker repo has been renamed to calico-containers
-  There are a number of other calico-container related repos that we should also point to
  -  calico-mesos
  -  calico-kubernetes
  -  calico-cni
  -  libcalico
  -  libnetwork-plugin

etc.

**Comment by fasaxc** [comment]
@eepyaich I think you'll get to close this one with the new docs integration

**Comment by djosborne** [comment]
This issue was moved to projectcalico/calico#69
